
// func002286
// function begins at statement 33847, parm_start=18384
// OP_CALL0	457	0	0
// OP_STORE_F	1	18385	0
// OP_MUL_F	18385	12465	18386
// OP_STORE_V	18386	4	0
// OP_CALL1	484	0	0
// OP_STORE_F	1	18385	0
// OP_LE	18385	213	18387
// OP_IFNOT	18387	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18388	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	140	0	0
// OP_LE	18385	214	18389
// OP_IFNOT	18389	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18390	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	133	0	0
// OP_LE	18385	216	18391
// OP_IFNOT	18391	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18392	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	126	0	0
// OP_LE	18385	228	18393
// OP_IFNOT	18393	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18394	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	119	0	0
// OP_LE	18385	229	18395
// OP_IFNOT	18395	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18396	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	112	0	0
// OP_LE	18385	230	18397
// OP_IFNOT	18397	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18398	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	105	0	0
// OP_LE	18385	231	18399
// OP_IFNOT	18399	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18400	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	98	0	0
// OP_LE	18385	232	18401
// OP_IFNOT	18401	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18402	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	91	0	0
// OP_LE	18385	217	18403
// OP_IFNOT	18403	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18404	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	84	0	0
// OP_LE	18385	234	18405
// OP_IFNOT	18405	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18406	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	77	0	0
// OP_LE	18385	235	18407
// OP_IFNOT	18407	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18408	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	70	0	0
// OP_LE	18385	236	18409
// OP_IFNOT	18409	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18377	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	63	0	0
// OP_LE	18385	791	18410
// OP_IFNOT	18410	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18381	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	56	0	0
// OP_LE	18385	792	18411
// OP_IFNOT	18411	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18412	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	49	0	0
// OP_LE	18385	5693	18413
// OP_IFNOT	18413	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18414	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	42	0	0
// OP_LE	18385	765	18415
// OP_IFNOT	18415	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18416	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	35	0	0
// OP_LE	18385	218	18417
// OP_IFNOT	18417	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18418	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	28	0	0
// OP_LE	18385	6892	18419
// OP_IFNOT	18419	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18420	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	21	0	0
// OP_LE	18385	6133	18421
// OP_IFNOT	18421	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18422	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	14	0	0
// OP_LE	18385	6895	18423
// OP_IFNOT	18423	6	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18424	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_GOTO	7	0	0
// OP_LE	18385	2323	18425
// OP_IFNOT	18425	5	0
// OP_STORE_V	18384	4	0
// OP_STORE_V	18426	7	0
// OP_STORE_V	16700	10	0
// OP_CALL3	1070	0	0
// OP_DONE	0	0	0
void (entity globaldef006474) func002286 = 
{
    local float globaldef006475;
    globaldef006475 = random();
    globaldef006475 = floor(globaldef006475 * 21);
    if(globaldef006475 <= FALSE)
    {
        func002366(globaldef006474, "hihi", globaldef005812);
    }
    else
    {
        if(globaldef006475 <= TRUE)
        {
            func002366(globaldef006474, "hehe", globaldef005812);
        }
        else
        {
            if(globaldef006475 <= FL_SWIM)
            {
                func002366(globaldef006474, "hahaha", globaldef005812);
            }
            else
            {
                if(globaldef006475 <= MOVETYPE_WALK)
                {
                    func002366(globaldef006474, "I'll put you in backpack mode", globaldef005812);
                }
                else
                {
                    if(globaldef006475 <= MOVETYPE_STEP)
                    {
                        func002366(globaldef006474, "you're boring", globaldef005812);
                    }
                    else
                    {
                        if(globaldef006475 <= MOVETYPE_FLY)
                        {
                            func002366(globaldef006474, "you really suck at quake", globaldef005812);
                        }
                        else
                        {
                            if(globaldef006475 <= MOVETYPE_TOSS)
                            {
                                func002366(globaldef006474, "let's rock", globaldef005812);
                            }
                            else
                            {
                                if(globaldef006475 <= MOVETYPE_PUSH)
                                {
                                    func002366(globaldef006474, "whoa!!", globaldef005812);
                                }
                                else
                                {
                                    if(globaldef006475 <= FL_CLIENT)
                                    {
                                        func002366(globaldef006474, "let's play another game", globaldef005812);
                                    }
                                    else
                                    {
                                        if(globaldef006475 <= MOVETYPE_FLYMISSILE)
                                        {
                                            func002366(globaldef006474, "I've had it for today", globaldef005812);
                                        }
                                        else
                                        {
                                            if(globaldef006475 <= MOVETYPE_BOUNCE)
                                            {
                                                func002366(globaldef006474, "DUH!!!", globaldef005812);
                                            }
                                            else
                                            {
                                                if(globaldef006475 <= MOVETYPE_BOUNCEMISSILE)
                                                {
                                                    func002366(globaldef006474, ":)", globaldef005812);
                                                }
                                                else
                                                {
                                                    if(globaldef006475 <= GLOBALDEFSEVENSEVENFOUR)
                                                    {
                                                        func002366(globaldef006474, "wow", globaldef005812);
                                                    }
                                                    else
                                                    {
                                                        if(globaldef006475 <= globaldef000775)
                                                        {
                                                            func002366(globaldef006474, "weeeee", globaldef005812);
                                                        }
                                                        else
                                                        {
                                                            if(globaldef006475 <= 14)
                                                            {
                                                                func002366(globaldef006474, "I'm on a roll", globaldef005812);
                                                            }
                                                            else
                                                            {
                                                                if(globaldef006475 <= GLOBALDEFSEVENFOUREIGHT)
                                                                {
                                                                    func002366(globaldef006474, "this rocks", globaldef005812);
                                                                }
                                                                else
                                                                {
                                                                    if(globaldef006475 <= FL_INWATER)
                                                                    {
                                                                        func002366(globaldef006474, "aaah", globaldef005812);
                                                                    }
                                                                    else
                                                                    {
                                                                        if(globaldef006475 <= 17)
                                                                        {
                                                                            func002366(globaldef006474, "groovy", globaldef005812);
                                                                        }
                                                                        else
                                                                        {
                                                                            if(globaldef006475 <= 18)
                                                                            {
                                                                                func002366(globaldef006474, "grrrrr", globaldef005812);
                                                                            }
                                                                            else
                                                                            {
                                                                                if(globaldef006475 <= 19)
                                                                                {
                                                                                    func002366(globaldef006474, "!!", globaldef005812);
                                                                                }
                                                                                else
                                                                                {
                                                                                    
                                                                                    if(globaldef006475 <= 20)
                                                                                    {
                                                                                        func002366(globaldef006474, "nice!", globaldef005812);
                                                                                    }
                                                                                    
                                                                                }
                                                                                
                                                                            }
                                                                            
                                                                        }
                                                                        
                                                                    }
                                                                    
                                                                }
                                                                
                                                            }
                                                            
                                                        }
                                                        
                                                    }
                                                    
                                                }
                                                
                                            }
                                            
                                        }
                                        
                                    }
                                    
                                }
                                
                            }
                            
                        }
                        
                    }
                    
                }
                
            }
            
        }
        
    }
    
};


// func002287
// function begins at statement 34000, parm_start=18428
// OP_NE_F	35	228	18430
// OP_NE_F	35	216	18431
// OP_AND	18430	18431	18432
// OP_IFNOT	18432	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18428	162	18433
// OP_BITAND	18433	18429	18434
// OP_IFNOT	18434	2	0
// OP_RETURN	214	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006496, float globaldef006497) func002287 = 
{
    
    if((deathmatch != MOVETYPE_WALK) && (deathmatch != FL_SWIM))
    {
        return FALSE;
    }
    
    
    if(globaldef006496.items & globaldef006497)
    {
        return TRUE;
    }
    
    return FALSE;
};


// func002288
// function begins at statement 34011, parm_start=18436
// OP_LOAD_ENT	18437	662	18439
// OP_EQ_E	18439	18436	18440
// OP_IFNOT	18440	6	0
// OP_LOAD_F	18437	663	18441
// OP_SUB_F	31	18438	18442
// OP_GT	18441	18442	18443
// OP_IFNOT	18443	2	0
// OP_RETURN	214	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006499, entity globaldef006500, float globaldef006501) func002288 = 
{
    
    if(globaldef006500.field000339 == globaldef006499)
    {
        
        if(globaldef006500.field000340 > (time - globaldef006501))
        {
            return TRUE;
        }
        
    }
    
    return FALSE;
};


// func002289
// function begins at statement 34021, parm_start=18444
// OP_STORE_V	18444	4	0
// OP_STORE_V	18445	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	25	0	0
// OP_LOAD_ENT	18445	201	18446
// OP_LOAD_S	18446	197	18447
// OP_IFNOT	18447	3	0
// OP_RETURN	213	0	0
// OP_GOTO	20	0	0
// OP_STORE_V	18444	4	0
// OP_STORE_V	18445	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18448
// OP_IFNOT	18448	3	0
// OP_RETURN	213	0	0
// OP_GOTO	13	0	0
// OP_LOAD_F	18445	438	18449
// OP_EQ_F	18449	282	18450
// OP_IFNOT	18450	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_LOAD_F	18445	438	18451
// OP_EQ_F	18451	284	18452
// OP_IFNOT	18452	3	0
// OP_RETURN	2323	0	0
// OP_GOTO	3	0	0
// OP_SUB_F	2323	214	18453
// OP_RETURN	18453	0	0
// OP_DONE	0	0	0
float (entity globaldef006502, entity globaldef006503) func002289 = 
{
    if(func002288(globaldef006502, globaldef006503, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(globaldef006503.owner.targetname)
        {
            return FALSE;
        }
        else
        {
            if(!func002456(globaldef006502, globaldef006503))
            {
                return FALSE;
            }
            else
            {
                if(globaldef006503.state == STATE_TOP)
                {
                    return FALSE;
                }
                else
                {
                    if(globaldef006503.state == STATE_UP)
                    {
                        return 20;
                    }
                    else
                    {
                        return 20 - TRUE;
                    }
                    
                }
                
            }
            
        }
        
    }
    
};


// func002290
// function begins at statement 34053, parm_start=18454
// OP_STORE_V	18454	4	0
// OP_STORE_V	18455	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	14	0	0
// OP_STORE_V	18454	4	0
// OP_STORE_V	18455	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18456
// OP_IFNOT	18456	3	0
// OP_RETURN	213	0	0
// OP_GOTO	7	0	0
// OP_LOAD_F	18455	163	18457
// OP_EQ_F	18457	251	18458
// OP_IFNOT	18458	3	0
// OP_RETURN	2323	0	0
// OP_GOTO	2	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006504, entity globaldef006505) func002290 = 
{
    if(func002288(globaldef006504, globaldef006505, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(!func002456(globaldef006504, globaldef006505))
        {
            return FALSE;
        }
        else
        {
            if(globaldef006505.takedamage == DAMAGE_YES)
            {
                return 20;
            }
            else
            {
                return FALSE;
            }
            
        }
        
    }
    
};


// func002291
// function begins at statement 34074, parm_start=18459
// OP_STORE_V	18459	4	0
// OP_STORE_V	18460	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	10	0	0
// OP_LOAD_F	18460	438	18461
// OP_EQ_F	18461	283	18462
// OP_IFNOT	18462	7	0
// OP_STORE_V	18459	4	0
// OP_STORE_V	18460	7	0
// OP_CALL2	1110	0	0
// OP_IFNOT	1	3	0
// OP_ADD_F	2323	214	18463
// OP_RETURN	18463	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006506, entity globaldef006507) func002291 = 
{
    if(func002288(globaldef006506, globaldef006507, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        
        if(globaldef006507.state == STATE_BOTTOM)
        {
            
            if(func002456(globaldef006506, globaldef006507))
            {
                return 20 + TRUE;
            }
            
        }
        
    }
    
    return FALSE;
};


// func002292
// function begins at statement 34092, parm_start=18464
// OP_STORE_V	18464	4	0
// OP_STORE_V	18465	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	13	0	0
// OP_STORE_V	18464	4	0
// OP_STORE_V	18465	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18466
// OP_IFNOT	18466	3	0
// OP_RETURN	213	0	0
// OP_GOTO	6	0	0
// OP_LOAD_ENT	18465	622	18467
// OP_IFNOT	18467	3	0
// OP_RETURN	213	0	0
// OP_GOTO	2	0	0
// OP_RETURN	2323	0	0
// OP_DONE	0	0	0
float (entity globaldef006508, entity globaldef006509) func002292 = 
{
    if(func002288(globaldef006508, globaldef006509, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(!func002456(globaldef006508, globaldef006509))
        {
            return FALSE;
        }
        else
        {
            if(globaldef006509.field000299)
            {
                return FALSE;
            }
            else
            {
                return 20;
            }
            
        }
        
    }
    
};


// func002293
// function begins at statement 34112, parm_start=18468
// OP_STORE_V	18468	4	0
// OP_STORE_V	18469	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	18	0	0
// OP_LOAD_F	18469	101	18470
// OP_LOAD_F	18468	108	18471
// OP_LOAD_F	18468	137	18472
// OP_ADD_F	18471	18472	18473
// OP_ADD_F	18473	793	18474
// OP_GT	18470	18474	18475
// OP_IFNOT	18475	3	0
// OP_RETURN	213	0	0
// OP_GOTO	9	0	0
// OP_STORE_V	18468	4	0
// OP_STORE_V	18469	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18476
// OP_IFNOT	18476	3	0
// OP_RETURN	213	0	0
// OP_GOTO	2	0	0
// OP_RETURN	2323	0	0
// OP_DONE	0	0	0
float (entity globaldef006510, entity globaldef006511) func002293 = 
{
    if(func002288(globaldef006510, globaldef006511, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(globaldef006511.absmax_z > ((globaldef006510.origin_z + globaldef006510.mins_z) + globaldef000776))
        {
            return FALSE;
        }
        else
        {
            if(!func002456(globaldef006510, globaldef006511))
            {
                return FALSE;
            }
            else
            {
                return 20;
            }
            
        }
        
    }
    
};


// func002294
// function begins at statement 34137, parm_start=18477
// OP_STORE_V	18477	4	0
// OP_STORE_V	18478	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	13	0	0
// OP_STORE_V	18477	4	0
// OP_STORE_V	18478	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18479
// OP_IFNOT	18479	3	0
// OP_RETURN	213	0	0
// OP_GOTO	6	0	0
// OP_LOAD_ENT	18478	622	18480
// OP_IFNOT	18480	3	0
// OP_RETURN	235	0	0
// OP_GOTO	2	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006512, entity globaldef006513) func002294 = 
{
    if(func002288(globaldef006512, globaldef006513, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(!func002456(globaldef006512, globaldef006513))
        {
            return FALSE;
        }
        else
        {
            if(globaldef006513.field000299)
            {
                return MOVETYPE_BOUNCE;
            }
            else
            {
                return 35;
            }
            
        }
        
    }
    
};


// func002295
// function begins at statement 34157, parm_start=18481
// OP_STORE_V	18481	4	0
// OP_STORE_V	18482	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	2	0
// OP_RETURN	213	0	0
// OP_LOAD_V	18482	94	18489
// OP_LOAD_V	18482	98	18492
// OP_ADD_V	18489	18492	18495
// OP_MUL_VF	18495	539	18498
// OP_STORE_V	18498	18486	0
// OP_LOAD_F	18482	97	18501
// OP_ADD_F	18501	214	18502
// OP_STORE_F	18502	18488	0
// OP_STORE_V	18486	18483	0
// OP_LOAD_F	18481	108	18503
// OP_STORE_F	18503	18485	0
// OP_LOAD_V	18481	105	18504
// OP_STORE_V	18504	4	0
// OP_STORE_V	18483	7	0
// OP_STORE_V	214	10	0
// OP_STORE_V	28	13	0
// OP_CALL4	466	0	0
// OP_EQ_F	70	214	18507
// OP_IFNOT	18507	24	0
// OP_STORE_V	18483	4	0
// OP_STORE_V	18486	7	0
// OP_STORE_V	214	10	0
// OP_STORE_V	28	13	0
// OP_CALL4	466	0	0
// OP_EQ_F	70	214	18508
// OP_IFNOT	18508	17	0
// OP_STORE_V	18486	4	0
// OP_CALL1	1111	0	0
// OP_STORE_F	1	18485	0
// OP_LOAD_F	28	97	18509
// OP_GT	18509	18485	18510
// OP_IFNOT	18510	3	0
// OP_LOAD_F	18481	97	18511
// OP_STORE_F	18511	18485	0
// OP_LOAD_F	18481	141	18512
// OP_LOAD_F	18481	137	18513
// OP_SUB_F	18512	18513	18514
// OP_ADD_F	18514	18485	18515
// OP_ADD_F	18515	793	18516
// OP_LT	18488	18516	18517
// OP_IFNOT	18517	2	0
// OP_RETURN	2323	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006514, entity globaldef006515) func002295 = 
{
    local vector globaldef006516;
    local vector globaldef006520;
    
    if(func002288(globaldef006514, globaldef006515, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    
    globaldef006520 = (globaldef006515.absmin + globaldef006515.absmax) * RA_PLAYERSTATTIME;
    globaldef006520_z = globaldef006515.absmin_z + TRUE;
    globaldef006516 = globaldef006520;
    globaldef006516_z = globaldef006514.origin_z;
    traceline(globaldef006514.origin, globaldef006516, TRUE, self);
    
    if(trace_fraction == TRUE)
    {
        traceline(globaldef006516, globaldef006520, TRUE, self);
        
        if(trace_fraction == TRUE)
        {
            globaldef006516_z = func002457(globaldef006520);
            
            if(self.absmin_z > globaldef006516_z)
            {
                globaldef006516_z = globaldef006514.absmin_z;
            }
            
            
            if(globaldef006520_z < (((globaldef006514.maxs_z - globaldef006514.mins_z) + globaldef006516_z) + globaldef000776))
            {
                return 20;
            }
            
        }
        
    }
    
    return FALSE;
};


// func002296
// function begins at statement 34207, parm_start=18518
// OP_LOAD_F	18519	163	18520
// OP_NE_F	18520	251	18521
// OP_IFNOT	18521	13	0
// OP_LOAD_F	18519	104	18522
// OP_NE_F	18522	238	18523
// OP_IFNOT	18523	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18519	101	18524
// OP_LOAD_F	18518	108	18525
// OP_LOAD_F	18518	137	18526
// OP_ADD_F	18525	18526	18527
// OP_ADD_F	18527	793	18528
// OP_GT	18524	18528	18529
// OP_IFNOT	18529	2	0
// OP_RETURN	213	0	0
// OP_STORE_V	18518	4	0
// OP_STORE_V	18519	7	0
// OP_STORE_V	791	10	0
// OP_CALL3	18435	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	15	0	0
// OP_STORE_V	18518	4	0
// OP_STORE_V	18519	7	0
// OP_CALL2	1110	0	0
// OP_NOT_F	1	0	18530
// OP_IFNOT	18530	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_CALL0	457	0	0
// OP_LT	1	6277	18531
// OP_IFNOT	18531	3	0
// OP_RETURN	5878	0	0
// OP_GOTO	3	0	0
// OP_SUB_F	2323	216	18532
// OP_RETURN	18532	0	0
// OP_DONE	0	0	0
float (entity globaldef006524, entity globaldef006525) func002296 = 
{
    
    if(globaldef006525.takedamage != DAMAGE_YES)
    {
        
        if(globaldef006525.solid != SOLID_TRIGGER)
        {
            return FALSE;
        }
        
        
        if(globaldef006525.absmax_z > ((globaldef006524.origin_z + globaldef006524.mins_z) + globaldef000776))
        {
            return FALSE;
        }
        
    }
    
    if(func002288(globaldef006524, globaldef006525, GLOBALDEFSEVENSEVENFOUR))
    {
        return FALSE;
    }
    else
    {
        if(!func002456(globaldef006524, globaldef006525))
        {
            return FALSE;
        }
        else
        {
            if(random() < 0.25)
            {
                return 35;
            }
            else
            {
                return 20 - FL_SWIM;
            }
            
        }
        
    }
    
};


// func002297
// function begins at statement 34244, parm_start=18533
// OP_LOAD_F	18533	162	18535
// OP_BITAND	18535	259	18536
// OP_NOT_F	18536	0	18537
// OP_LOAD_F	18534	162	18538
// OP_BITAND	18538	259	18539
// OP_AND	18537	18539	18540
// OP_IFNOT	18540	2	0
// OP_RETURN	9989	0	0
// OP_LOAD_F	18533	162	18541
// OP_BITAND	18541	260	18542
// OP_NOT_F	18542	0	18543
// OP_LOAD_F	18534	162	18544
// OP_BITAND	18544	260	18545
// OP_AND	18543	18545	18546
// OP_IFNOT	18546	2	0
// OP_RETURN	9987	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006526, entity globaldef006527) func002297 = 
{
    
    if((!(globaldef006526.items & IT_ROCKET_LAUNCHER)) && (globaldef006527.items & IT_ROCKET_LAUNCHER))
    {
        return 99;
    }
    
    
    if((!(globaldef006526.items & IT_LIGHTNING)) && (globaldef006527.items & IT_LIGHTNING))
    {
        return 98;
    }
    
    return 35;
};


// func002298
// function begins at statement 34262, parm_start=18547
// OP_RETURN	1997	0	0
// OP_DONE	0	0	0
float (entity globaldef006528, entity globaldef006529) func002298 = 
{
    return 100;
};


// func002299
// function begins at statement 34264, parm_start=18549
// OP_LOAD_F	18549	152	18551
// OP_LT	18551	2019	18552
// OP_IFNOT	18552	3	0
// OP_RETURN	9974	0	0
// OP_GOTO	7	0	0
// OP_LOAD_F	18549	152	18553
// OP_LT	18553	1997	18554
// OP_IFNOT	18554	3	0
// OP_RETURN	9671	0	0
// OP_GOTO	2	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006530, entity globaldef006531) func002299 = 
{
    if(globaldef006530.health < 60)
    {
        return 91;
    }
    else
    {
        if(globaldef006530.health < 100)
        {
            return 34;
        }
        else
        {
            return FALSE;
        }
        
    }
    
};


// func002300
// function begins at statement 34276, parm_start=18555
// OP_LOAD_F	18555	152	18557
// OP_LT	18557	2019	18558
// OP_IFNOT	18558	3	0
// OP_RETURN	9976	0	0
// OP_GOTO	7	0	0
// OP_LOAD_F	18555	152	18559
// OP_LT	18559	1997	18560
// OP_IFNOT	18560	3	0
// OP_RETURN	5878	0	0
// OP_GOTO	2	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006532, entity globaldef006533) func002300 = 
{
    if(globaldef006532.health < 60)
    {
        return 92;
    }
    else
    {
        if(globaldef006532.health < 100)
        {
            return 35;
        }
        else
        {
            return FALSE;
        }
        
    }
    
};


// func002301
// function begins at statement 34288, parm_start=18561
// OP_LOAD_F	18561	159	18563
// OP_GE	18563	2044	18564
// OP_IFNOT	18564	3	0
// OP_RETURN	213	0	0
// OP_GOTO	7	0	0
// OP_LOAD_F	18561	159	18565
// OP_GT	18565	3584	18566
// OP_IFNOT	18566	3	0
// OP_RETURN	6133	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9671	0	0
// OP_DONE	0	0	0
float (entity globaldef006534, entity globaldef006535) func002301 = 
{
    if(globaldef006534.ammo_nails >= 200)
    {
        return FALSE;
    }
    else
    {
        if(globaldef006534.ammo_nails > 120)
        {
            return 18;
        }
        else
        {
            return 34;
        }
        
    }
    
};


// func002302
// function begins at statement 34300, parm_start=18567
// OP_LOAD_F	18567	158	18569
// OP_GE	18569	1997	18570
// OP_IFNOT	18570	3	0
// OP_RETURN	213	0	0
// OP_GOTO	7	0	0
// OP_LOAD_F	18567	158	18571
// OP_GT	18571	1470	18572
// OP_IFNOT	18572	3	0
// OP_RETURN	6133	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9671	0	0
// OP_DONE	0	0	0
float (entity globaldef006536, entity globaldef006537) func002302 = 
{
    if(globaldef006536.ammo_shells >= 100)
    {
        return FALSE;
    }
    else
    {
        if(globaldef006536.ammo_shells > 50)
        {
            return 18;
        }
        else
        {
            return 34;
        }
        
    }
    
};


// func002303
// function begins at statement 34312, parm_start=18573
// OP_LOAD_F	18573	161	18575
// OP_GE	18575	1997	18576
// OP_IFNOT	18576	3	0
// OP_RETURN	213	0	0
// OP_GOTO	10	0	0
// OP_LOAD_F	18573	162	18577
// OP_BITAND	18577	260	18578
// OP_LOAD_F	18573	161	18579
// OP_LT	18579	309	18580
// OP_AND	18578	18580	18581
// OP_IFNOT	18581	3	0
// OP_RETURN	2598	0	0
// OP_GOTO	2	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006538, entity globaldef006539) func002303 = 
{
    if(globaldef006538.ammo_cells >= 100)
    {
        return FALSE;
    }
    else
    {
        if((globaldef006538.items & IT_LIGHTNING) && (globaldef006538.ammo_cells < SVC_INTERMISSION))
        {
            return 45;
        }
        else
        {
            return 35;
        }
        
    }
    
};


// func002304
// function begins at statement 34327, parm_start=18582
// OP_LOAD_F	18582	160	18584
// OP_GE	18584	1997	18585
// OP_IFNOT	18585	3	0
// OP_RETURN	213	0	0
// OP_GOTO	10	0	0
// OP_LOAD_F	18582	162	18586
// OP_BITAND	18586	259	18587
// OP_LOAD_F	18582	160	18588
// OP_LT	18588	2323	18589
// OP_AND	18587	18589	18590
// OP_IFNOT	18590	3	0
// OP_RETURN	1470	0	0
// OP_GOTO	2	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006540, entity globaldef006541) func002304 = 
{
    if(globaldef006540.ammo_rockets >= 100)
    {
        return FALSE;
    }
    else
    {
        if((globaldef006540.items & IT_ROCKET_LAUNCHER) && (globaldef006540.ammo_rockets < 20))
        {
            return 50;
        }
        else
        {
            return 35;
        }
        
    }
    
};


// func002305
// function begins at statement 34342, parm_start=18591
// OP_STORE_V	18591	4	0
// OP_STORE_V	259	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_LOAD_F	18591	162	18593
// OP_BITAND	18593	259	18594
// OP_NOT_F	18594	0	18595
// OP_IFNOT	18595	3	0
// OP_RETURN	1997	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9657	0	0
// OP_DONE	0	0	0
float (entity globaldef006542, entity globaldef006543) func002305 = 
{
    if(func002287(globaldef006542, IT_ROCKET_LAUNCHER))
    {
        return FALSE;
    }
    else
    {
        if(!(globaldef006542.items & IT_ROCKET_LAUNCHER))
        {
            return 100;
        }
        else
        {
            return 37;
        }
        
    }
    
};


// func002306
// function begins at statement 34356, parm_start=18596
// OP_STORE_V	18596	4	0
// OP_STORE_V	260	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_LOAD_F	18596	162	18598
// OP_BITAND	18598	260	18599
// OP_NOT_F	18599	0	18600
// OP_IFNOT	18600	3	0
// OP_RETURN	9981	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9657	0	0
// OP_DONE	0	0	0
float (entity globaldef006544, entity globaldef006545) func002306 = 
{
    if(func002287(globaldef006544, IT_LIGHTNING))
    {
        return FALSE;
    }
    else
    {
        if(!(globaldef006544.items & IT_LIGHTNING))
        {
            return 95;
        }
        else
        {
            return 37;
        }
        
    }
    
};


// func002307
// function begins at statement 34370, parm_start=18601
// OP_STORE_V	18601	4	0
// OP_STORE_V	258	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_LOAD_F	18601	162	18603
// OP_BITAND	18603	258	18604
// OP_NOT_F	18604	0	18605
// OP_IFNOT	18605	3	0
// OP_RETURN	2658	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9655	0	0
// OP_DONE	0	0	0
float (entity globaldef006546, entity globaldef006547) func002307 = 
{
    if(func002287(globaldef006546, IT_GRENADE_LAUNCHER))
    {
        return FALSE;
    }
    else
    {
        if(!(globaldef006546.items & IT_GRENADE_LAUNCHER))
        {
            return 90;
        }
        else
        {
            return 36;
        }
        
    }
    
};


// func002308
// function begins at statement 34384, parm_start=18606
// OP_STORE_V	18606	4	0
// OP_STORE_V	256	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	2	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006548, entity globaldef006549) func002308 = 
{
    if(func002287(globaldef006548, IT_NAILGUN))
    {
        return FALSE;
    }
    else
    {
        return 35;
    }
    
};


// func002309
// function begins at statement 34392, parm_start=18608
// OP_STORE_V	18608	4	0
// OP_STORE_V	257	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	8	0	0
// OP_LOAD_F	18608	162	18610
// OP_BITAND	18610	257	18611
// OP_NOT_F	18611	0	18612
// OP_IFNOT	18612	3	0
// OP_RETURN	9963	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9655	0	0
// OP_DONE	0	0	0
float (entity globaldef006550, entity globaldef006551) func002309 = 
{
    if(func002287(globaldef006550, IT_SUPER_NAILGUN))
    {
        return FALSE;
    }
    else
    {
        if(!(globaldef006550.items & IT_SUPER_NAILGUN))
        {
            return 85;
        }
        else
        {
            return 36;
        }
        
    }
    
};


// func002310
// function begins at statement 34406, parm_start=18613
// OP_STORE_V	18613	4	0
// OP_STORE_V	255	7	0
// OP_CALL2	18427	0	0
// OP_IFNOT	1	3	0
// OP_RETURN	213	0	0
// OP_GOTO	2	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006552, entity globaldef006553) func002310 = 
{
    if(func002287(globaldef006552, IT_SUPER_SHOTGUN))
    {
        return FALSE;
    }
    else
    {
        return 35;
    }
    
};


// func002311
// function begins at statement 34414, parm_start=18615
// OP_LOAD_F	18616	188	18618
// OP_MUL_F	18618	3409	18619
// OP_LOAD_F	18615	188	18620
// OP_LOAD_F	18615	187	18621
// OP_MUL_F	18620	18621	18622
// OP_SUB_F	18619	18622	18623
// OP_MUL_F	216	18623	18624
// OP_STORE_F	18624	18617	0
// OP_LT	18617	213	18625
// OP_IFNOT	18625	2	0
// OP_STORE_F	213	18617	0
// OP_RETURN	18617	0	0
// OP_DONE	0	0	0
float (entity globaldef006554, entity globaldef006555) func002311 = 
{
    local float globaldef006556;
    globaldef006556 = FL_SWIM * ((globaldef006555.armorvalue * 0.3) - (globaldef006554.armorvalue * globaldef006554.armortype));
    
    if(globaldef006556 < FALSE)
    {
        globaldef006556 = FALSE;
    }
    
    return globaldef006556;
};


// func002312
// function begins at statement 34427, parm_start=18626
// OP_LOAD_F	18627	188	18629
// OP_MUL_F	18629	4474	18630
// OP_LOAD_F	18626	188	18631
// OP_LOAD_F	18626	187	18632
// OP_MUL_F	18631	18632	18633
// OP_SUB_F	18630	18633	18634
// OP_MUL_F	216	18634	18635
// OP_STORE_F	18635	18628	0
// OP_LT	18628	213	18636
// OP_IFNOT	18636	2	0
// OP_STORE_F	213	18628	0
// OP_RETURN	18628	0	0
// OP_DONE	0	0	0
float (entity globaldef006557, entity globaldef006558) func002312 = 
{
    local float globaldef006559;
    globaldef006559 = FL_SWIM * ((globaldef006558.armorvalue * 0.6) - (globaldef006557.armorvalue * globaldef006557.armortype));
    
    if(globaldef006559 < FALSE)
    {
        globaldef006559 = FALSE;
    }
    
    return globaldef006559;
};


// func002313
// function begins at statement 34440, parm_start=18637
// OP_LOAD_F	18638	188	18640
// OP_MUL_F	18640	4478	18641
// OP_LOAD_F	18637	188	18642
// OP_LOAD_F	18637	187	18643
// OP_MUL_F	18642	18643	18644
// OP_SUB_F	18641	18644	18645
// OP_MUL_F	216	18645	18646
// OP_STORE_F	18646	18639	0
// OP_LT	18639	213	18647
// OP_IFNOT	18647	2	0
// OP_STORE_F	213	18639	0
// OP_RETURN	18639	0	0
// OP_DONE	0	0	0
float (entity globaldef006560, entity globaldef006561) func002313 = 
{
    local float globaldef006562;
    globaldef006562 = FL_SWIM * ((globaldef006561.armorvalue * 0.8) - (globaldef006560.armorvalue * globaldef006560.armortype));
    
    if(globaldef006562 < FALSE)
    {
        globaldef006562 = FALSE;
    }
    
    return globaldef006562;
};


// func002314
// function begins at statement 34453, parm_start=18648
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006563, entity globaldef006564) func002314 = 
{
    return 35;
};


// func002315
// function begins at statement 34455, parm_start=18650
// OP_ADD_F	1997	228	18652
// OP_RETURN	18652	0	0
// OP_DONE	0	0	0
float (entity globaldef006565, entity globaldef006566) func002315 = 
{
    return 100 + MOVETYPE_WALK;
};


// func002316
// function begins at statement 34458, parm_start=18653
// OP_ADD_F	1997	230	18655
// OP_RETURN	18655	0	0
// OP_DONE	0	0	0
float (entity globaldef006567, entity globaldef006568) func002316 = 
{
    return 100 + MOVETYPE_FLY;
};


// func002317
// function begins at statement 34461, parm_start=18656
// OP_ADD_F	1997	231	18658
// OP_RETURN	18658	0	0
// OP_DONE	0	0	0
float (entity globaldef006569, entity globaldef006570) func002317 = 
{
    return 100 + MOVETYPE_TOSS;
};


// func002318
// function begins at statement 34464, parm_start=18659
// OP_RETURN	9951	0	0
// OP_DONE	0	0	0
float (entity globaldef006571, entity globaldef006572) func002318 = 
{
    return 77;
};


// func002319
// function begins at statement 34466, parm_start=18661
// OP_RETURN	9919	0	0
// OP_DONE	0	0	0
float (entity globaldef006573, entity globaldef006574) func002319 = 
{
    return 55;
};


// func002320
// function begins at statement 34468, parm_start=18663
// OP_RETURN	1470	0	0
// OP_DONE	0	0	0
float (entity globaldef006575, entity globaldef006576) func002320 = 
{
    return 50;
};


// func002321
// function begins at statement 34470, parm_start=18665
// OP_RETURN	1536	0	0
// OP_DONE	0	0	0
float (entity globaldef006577, entity globaldef006578) func002321 = 
{
    return 70;
};


// func002322
// function begins at statement 34472, parm_start=18667
// OP_RETURN	2805	0	0
// OP_DONE	0	0	0
float (entity globaldef006579, entity globaldef006580) func002322 = 
{
    return 80;
};


// func002323
// function begins at statement 34474, parm_start=18669
// OP_RETURN	1997	0	0
// OP_DONE	0	0	0
float (entity globaldef006581, entity globaldef006582) func002323 = 
{
    return 100;
};


// func002324
// function begins at statement 34476, parm_start=18671
// OP_RETURN	9173	0	0
// OP_DONE	0	0	0
float (entity globaldef006583, entity globaldef006584) func002324 = 
{
    return 75;
};


// func002325
// function begins at statement 34478, parm_start=18673
// OP_RETURN	2658	0	0
// OP_DONE	0	0	0
float (entity globaldef006585, entity globaldef006586) func002325 = 
{
    return 90;
};


// func002326
// function begins at statement 34480, parm_start=18675
// OP_RETURN	9987	0	0
// OP_DONE	0	0	0
float (entity globaldef006587, entity globaldef006588) func002326 = 
{
    return 98;
};


// func002327
// function begins at statement 34482, parm_start=18677
// OP_LOAD_F	18678	150	18679
// OP_ADD_F	31	235	18680
// OP_LT	18679	18680	18681
// OP_IFNOT	18681	2	0
// OP_RETURN	5487	0	0
// OP_RETURN	235	0	0
// OP_DONE	0	0	0
float (entity globaldef006589, entity globaldef006590) func002327 = 
{
    
    if(globaldef006590.nextthink < (time + MOVETYPE_BOUNCE))
    {
        return 73;
    }
    
    return MOVETYPE_BOUNCE;
};


// func002328
// function begins at statement 34489, parm_start=18682
// OP_LOAD_F	18683	150	18684
// OP_ADD_F	31	235	18685
// OP_LT	18684	18685	18686
// OP_IFNOT	18686	2	0
// OP_RETURN	9961	0	0
// OP_RETURN	765	0	0
// OP_DONE	0	0	0
float (entity globaldef006591, entity globaldef006592) func002328 = 
{
    
    if(globaldef006592.nextthink < (time + MOVETYPE_BOUNCE))
    {
        return 83;
    }
    
    return GLOBALDEFSEVENFOUREIGHT;
};


// func002329
// function begins at statement 34496, parm_start=18687
// OP_LOAD_F	18688	150	18689
// OP_ADD_F	31	235	18690
// OP_LT	18689	18690	18691
// OP_IFNOT	18691	2	0
// OP_RETURN	9978	0	0
// OP_RETURN	2323	0	0
// OP_DONE	0	0	0
float (entity globaldef006593, entity globaldef006594) func002329 = 
{
    
    if(globaldef006594.nextthink < (time + MOVETYPE_BOUNCE))
    {
        return 93;
    }
    
    return 20;
};


// func002330
// function begins at statement 34503, parm_start=18693
// OP_LOAD_F	18693	162	18695
// OP_BITAND	18695	260	18696
// OP_NOT_F	18696	0	18697
// OP_IFNOT	18697	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18693	161	18698
// OP_LT	18698	214	18699
// OP_IFNOT	18699	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18693	162	18700
// OP_BITAND	18700	273	18701
// OP_NOT_F	18701	0	18702
// OP_IFNOT	18702	5	0
// OP_LOAD_F	18693	189	18703
// OP_GE	18703	216	18704
// OP_IFNOT	18704	2	0
// OP_RETURN	235	0	0
// OP_LOAD_ENT	18693	181	18705
// OP_LOAD_V	18705	105	18706
// OP_LOAD_V	18693	105	18709
// OP_SUB_V	18706	18709	18712
// OP_STORE_V	18712	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	18694	0
// OP_LT	18694	740	18715
// OP_IFNOT	18715	26	0
// OP_LOAD_ENT	18693	181	18716
// OP_LOAD_F	18716	108	18717
// OP_LOAD_F	18693	108	18718
// OP_ADD_F	18718	2805	18719
// OP_GT	18717	18719	18720
// OP_IFNOT	18720	19	0
// OP_BITAND	821	767	18721
// OP_IFNOT	18721	5	0
// OP_LOAD_F	18693	588	18722
// OP_GT	18722	216	18723
// OP_IFNOT	18723	2	0
// OP_RETURN	8204	0	0
// OP_LOAD_F	18693	154	18724
// OP_NE_F	18724	260	18725
// OP_IFNOT	18725	6	0
// OP_CALL0	5370	0	0
// OP_MUL_F	1	216	18726
// OP_ADD_F	2805	18726	18727
// OP_RETURN	18727	0	0
// OP_GOTO	5	0	0
// OP_CALL0	5370	0	0
// OP_MUL_F	1	216	18728
// OP_ADD_F	8204	18728	18729
// OP_RETURN	18729	0	0
// OP_RETURN	1536	0	0
// OP_RETURN	746	0	0
// OP_DONE	0	0	0
float (entity globaldef006596) func002330 = 
{
    local float globaldef006597;
    
    if(!(globaldef006596.items & IT_LIGHTNING))
    {
        return FALSE;
    }
    
    
    if(globaldef006596.ammo_cells < TRUE)
    {
        return FALSE;
    }
    
    
    if(!(globaldef006596.items & IT_INVULNERABILITY))
    {
        
        if(globaldef006596.waterlevel >= FL_SWIM)
        {
            return MOVETYPE_BOUNCE;
        }
        
    }
    
    globaldef006597 = vlen(globaldef006596.enemy.origin - globaldef006596.origin);
    
    if(globaldef006597 < GLOBALDEFSEVENTWOTHREE)
    {
        
        if(globaldef006596.enemy.origin_z > (globaldef006596.origin_z + 80))
        {
            
            if(globaldef000804 & OBOT_ROCKETARENA)
            {
                
                if(globaldef006596.field000265 > FL_SWIM)
                {
                    return 81;
                }
                
            }
            
            if(globaldef006596.weapon != IT_LIGHTNING)
            {
                return 80 + (func000249() * FL_SWIM);
            }
            else
            {
                return 81 + (func000249() * FL_SWIM);
            }
            
        }
        
        return 70;
    }
    
    return GLOBALDEFSEVENTWONINE;
};


// func002331
// function begins at statement 34556, parm_start=18731
// OP_LOAD_F	18731	162	18734
// OP_BITAND	18734	259	18735
// OP_NOT_F	18735	0	18736
// OP_IFNOT	18736	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18731	160	18737
// OP_LT	18737	214	18738
// OP_IFNOT	18738	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18731	152	18739
// OP_MUL_F	18739	539	18740
// OP_SUB_F	1296	18740	18741
// OP_LOAD_F	18731	188	18742
// OP_LOAD_F	18731	187	18743
// OP_MUL_F	18742	18743	18744
// OP_SUB_F	18741	18744	18745
// OP_STORE_F	18745	18732	0
// OP_LOAD_F	18731	162	18746
// OP_BITAND	18746	275	18747
// OP_IFNOT	18747	3	0
// OP_MUL_F	18732	216	18748
// OP_STORE_F	18748	18732	0
// OP_LOAD_ENT	18731	181	18749
// OP_LOAD_V	18749	105	18750
// OP_LOAD_V	18731	105	18753
// OP_SUB_V	18750	18753	18756
// OP_STORE_V	18756	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	18733	0
// OP_LT	18733	18732	18759
// OP_IFNOT	18759	2	0
// OP_RETURN	309	0	0
// OP_RETURN	2805	0	0
// OP_DONE	0	0	0
float (entity globaldef006599) func002331 = 
{
    local float globaldef006600;
    local float globaldef006601;
    
    if(!(globaldef006599.items & IT_ROCKET_LAUNCHER))
    {
        return FALSE;
    }
    
    
    if(globaldef006599.ammo_rockets < TRUE)
    {
        return FALSE;
    }
    
    globaldef006600 = (180 - (globaldef006599.health * RA_PLAYERSTATTIME)) - (globaldef006599.armorvalue * globaldef006599.armortype);
    
    if(globaldef006599.items & IT_QUAD)
    {
        globaldef006600 = globaldef006600 * FL_SWIM;
    }
    
    globaldef006601 = vlen(globaldef006599.enemy.origin - globaldef006599.origin);
    
    if(globaldef006601 < globaldef006600)
    {
        return SVC_INTERMISSION;
    }
    
    return 80;
};


// func002332
// function begins at statement 34590, parm_start=18761
// OP_LOAD_F	18761	162	18763
// OP_BITAND	18763	258	18764
// OP_NOT_F	18764	0	18765
// OP_IFNOT	18765	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18761	160	18766
// OP_LT	18766	214	18767
// OP_IFNOT	18767	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18761	181	18768
// OP_LOAD_F	18768	108	18769
// OP_LOAD_F	18761	108	18770
// OP_ADD_F	18770	14518	18771
// OP_GT	18769	18771	18772
// OP_IFNOT	18772	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18761	181	18773
// OP_LOAD_V	18773	105	18774
// OP_LOAD_V	18761	105	18777
// OP_SUB_V	18774	18777	18780
// OP_STORE_V	18780	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	18762	0
// OP_GT	18762	740	18783
// OP_IFNOT	18783	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18761	181	18784
// OP_LOAD_F	18784	108	18785
// OP_LOAD_F	18761	108	18786
// OP_SUB_F	18786	2044	18787
// OP_LT	18785	18787	18788
// OP_IFNOT	18788	5	0
// OP_CALL0	5370	0	0
// OP_MUL_F	1	236	18789
// OP_ADD_F	1536	18789	18790
// OP_RETURN	18790	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006603) func002332 = 
{
    local float globaldef006604;
    
    if(!(globaldef006603.items & IT_GRENADE_LAUNCHER))
    {
        return FALSE;
    }
    
    
    if(globaldef006603.ammo_rockets < TRUE)
    {
        return FALSE;
    }
    
    
    if(globaldef006603.enemy.origin_z > (globaldef006603.origin_z + 175))
    {
        return FALSE;
    }
    
    globaldef006604 = vlen(globaldef006603.enemy.origin - globaldef006603.origin);
    
    if(globaldef006604 > GLOBALDEFSEVENTWOTHREE)
    {
        return FALSE;
    }
    
    
    if(globaldef006603.enemy.origin_z < (globaldef006603.origin_z - 200))
    {
        return 70 + (func000249() * MOVETYPE_BOUNCEMISSILE);
    }
    
    return 35;
};


// func002333
// function begins at statement 34628, parm_start=18792
// OP_LOAD_F	18792	162	18793
// OP_BITAND	18793	257	18794
// OP_NOT_F	18794	0	18795
// OP_IFNOT	18795	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18792	159	18796
// OP_LT	18796	216	18797
// OP_IFNOT	18797	2	0
// OP_RETURN	213	0	0
// OP_RETURN	9934	0	0
// OP_DONE	0	0	0
float (entity globaldef006606) func002333 = 
{
    
    if(!(globaldef006606.items & IT_SUPER_NAILGUN))
    {
        return FALSE;
    }
    
    
    if(globaldef006606.ammo_nails < FL_SWIM)
    {
        return FALSE;
    }
    
    return 65;
};


// func002334
// function begins at statement 34639, parm_start=18799
// OP_LOAD_F	18799	162	18800
// OP_BITAND	18800	256	18801
// OP_NOT_F	18801	0	18802
// OP_IFNOT	18802	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18799	159	18803
// OP_LT	18803	214	18804
// OP_IFNOT	18804	2	0
// OP_RETURN	213	0	0
// OP_RETURN	1470	0	0
// OP_DONE	0	0	0
float (entity globaldef006608) func002334 = 
{
    
    if(!(globaldef006608.items & IT_NAILGUN))
    {
        return FALSE;
    }
    
    
    if(globaldef006608.ammo_nails < TRUE)
    {
        return FALSE;
    }
    
    return 50;
};


// func002335
// function begins at statement 34650, parm_start=18806
// OP_LOAD_F	18806	162	18808
// OP_BITAND	18808	255	18809
// OP_NOT_F	18809	0	18810
// OP_IFNOT	18810	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18806	158	18811
// OP_LT	18811	216	18812
// OP_IFNOT	18812	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18806	181	18813
// OP_LOAD_V	18813	105	18814
// OP_LOAD_V	18806	105	18817
// OP_SUB_V	18814	18817	18820
// OP_STORE_V	18820	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	18807	0
// OP_GT	18807	740	18823
// OP_IFNOT	18823	3	0
// OP_RETURN	305	0	0
// OP_GOTO	2	0	0
// OP_RETURN	9919	0	0
// OP_DONE	0	0	0
float (entity globaldef006610) func002335 = 
{
    local float globaldef006611;
    
    if(!(globaldef006610.items & IT_SUPER_SHOTGUN))
    {
        return FALSE;
    }
    
    
    if(globaldef006610.ammo_shells < FL_SWIM)
    {
        return FALSE;
    }
    
    globaldef006611 = vlen(globaldef006610.enemy.origin - globaldef006610.origin);
    if(globaldef006611 > GLOBALDEFSEVENTWOTHREE)
    {
        return SVC_SIGNONNUM;
    }
    else
    {
        return 55;
    }
    
};


// func002336
// function begins at statement 34672, parm_start=18825
// OP_LOAD_F	18825	162	18826
// OP_BITAND	18826	254	18827
// OP_NOT_F	18827	0	18828
// OP_IFNOT	18828	2	0
// OP_RETURN	213	0	0
// OP_LOAD_F	18825	158	18829
// OP_LT	18829	214	18830
// OP_IFNOT	18830	2	0
// OP_RETURN	213	0	0
// OP_RETURN	5878	0	0
// OP_DONE	0	0	0
float (entity globaldef006613) func002336 = 
{
    
    if(!(globaldef006613.items & IT_SHOTGUN))
    {
        return FALSE;
    }
    
    
    if(globaldef006613.ammo_shells < TRUE)
    {
        return FALSE;
    }
    
    return 35;
};


// func002337
// function begins at statement 34683, parm_start=18832
// OP_LOAD_F	18832	162	18834
// OP_BITAND	18834	253	18835
// OP_NOT_F	18835	0	18836
// OP_IFNOT	18836	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18832	181	18837
// OP_LOAD_V	18837	105	18838
// OP_LOAD_V	18832	105	18841
// OP_SUB_V	18838	18841	18844
// OP_STORE_V	18844	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	18833	0
// OP_LT	18833	1997	18847
// OP_IFNOT	18847	3	0
// OP_RETURN	2323	0	0
// OP_GOTO	2	0	0
// OP_RETURN	230	0	0
// OP_DONE	0	0	0
float (entity globaldef006615) func002337 = 
{
    local float globaldef006616;
    
    if(!(globaldef006615.items & IT_AXE))
    {
        return FALSE;
    }
    
    globaldef006616 = vlen(globaldef006615.enemy.origin - globaldef006615.origin);
    if(globaldef006616 < 100)
    {
        return 20;
    }
    else
    {
        return MOVETYPE_FLY;
    }
    
};


// func002338
// function begins at statement 34701, parm_start=18848
// OP_STORE_F	213	18849	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18692	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18852
// OP_IFNOT	18852	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	260	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18730	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18853
// OP_IFNOT	18853	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	259	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18760	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18854
// OP_IFNOT	18854	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	258	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18791	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18855
// OP_IFNOT	18855	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	257	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18798	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18856
// OP_IFNOT	18856	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	256	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18805	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18857
// OP_IFNOT	18857	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	255	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18824	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18858
// OP_IFNOT	18858	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	254	18851	0
// OP_STORE_V	18848	4	0
// OP_CALL1	18831	0	0
// OP_STORE_F	1	18850	0
// OP_GT	18850	18849	18859
// OP_IFNOT	18859	3	0
// OP_STORE_F	18850	18849	0
// OP_STORE_F	253	18851	0
// OP_ADDRESS	18848	154	18860
// OP_STOREP_F	18851	18860	0
// OP_DONE	0	0	0
void (entity globaldef006617) func002338 = 
{
    local float globaldef006618;
    local float globaldef006619;
    local float globaldef006620;
    globaldef006618 = FALSE;
    globaldef006619 = func002330(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_LIGHTNING;
    }
    
    globaldef006619 = func002331(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_ROCKET_LAUNCHER;
    }
    
    globaldef006619 = func002332(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_GRENADE_LAUNCHER;
    }
    
    globaldef006619 = func002333(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_SUPER_NAILGUN;
    }
    
    globaldef006619 = func002334(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_NAILGUN;
    }
    
    globaldef006619 = func002335(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_SUPER_SHOTGUN;
    }
    
    globaldef006619 = func002336(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_SHOTGUN;
    }
    
    globaldef006619 = func002337(globaldef006617);
    
    if(globaldef006619 > globaldef006618)
    {
        globaldef006618 = globaldef006619;
        globaldef006620 = IT_AXE;
    }
    
    globaldef006617.weapon = globaldef006620;
};


// func002339
// function begins at statement 34761, parm_start=18861
// OP_LOAD_F	18861	160	18862
// OP_GE	18862	214	18863
// OP_LOAD_F	18861	162	18864
// OP_BITAND	18864	259	18865
// OP_AND	18863	18865	18866
// OP_IFNOT	18866	2	0
// OP_RETURN	259	0	0
// OP_LOAD_F	18861	161	18867
// OP_GE	18867	214	18868
// OP_LOAD_F	18861	162	18869
// OP_BITAND	18869	260	18870
// OP_AND	18868	18870	18871
// OP_IFNOT	18871	9	0
// OP_LOAD_F	18861	189	18872
// OP_LT	18872	216	18873
// OP_IFNOT	18873	2	0
// OP_RETURN	260	0	0
// OP_LOAD_F	18861	162	18874
// OP_BITAND	18874	273	18875
// OP_IFNOT	18875	2	0
// OP_RETURN	260	0	0
// OP_LOAD_F	18861	159	18876
// OP_GE	18876	216	18877
// OP_LOAD_F	18861	162	18878
// OP_BITAND	18878	257	18879
// OP_AND	18877	18879	18880
// OP_IFNOT	18880	2	0
// OP_RETURN	257	0	0
// OP_LOAD_F	18861	160	18881
// OP_GE	18881	214	18882
// OP_LOAD_F	18861	162	18883
// OP_BITAND	18883	258	18884
// OP_AND	18882	18884	18885
// OP_IFNOT	18885	2	0
// OP_RETURN	258	0	0
// OP_LOAD_F	18861	158	18886
// OP_GE	18886	216	18887
// OP_LOAD_F	18861	162	18888
// OP_BITAND	18888	255	18889
// OP_AND	18887	18889	18890
// OP_IFNOT	18890	2	0
// OP_RETURN	255	0	0
// OP_LOAD_F	18861	159	18891
// OP_GE	18891	214	18892
// OP_LOAD_F	18861	162	18893
// OP_BITAND	18893	256	18894
// OP_AND	18892	18894	18895
// OP_IFNOT	18895	2	0
// OP_RETURN	256	0	0
// OP_LOAD_F	18861	158	18896
// OP_GE	18896	214	18897
// OP_LOAD_F	18861	162	18898
// OP_BITAND	18898	254	18899
// OP_AND	18897	18899	18900
// OP_IFNOT	18900	2	0
// OP_RETURN	254	0	0
// OP_RETURN	253	0	0
// OP_DONE	0	0	0
float (entity globaldef006621) func002339 = 
{
    
    if((globaldef006621.ammo_rockets >= TRUE) && (globaldef006621.items & IT_ROCKET_LAUNCHER))
    {
        return IT_ROCKET_LAUNCHER;
    }
    
    
    if((globaldef006621.ammo_cells >= TRUE) && (globaldef006621.items & IT_LIGHTNING))
    {
        
        if(globaldef006621.waterlevel < FL_SWIM)
        {
            return IT_LIGHTNING;
        }
        
        
        if(globaldef006621.items & IT_INVULNERABILITY)
        {
            return IT_LIGHTNING;
        }
        
    }
    
    
    if((globaldef006621.ammo_nails >= FL_SWIM) && (globaldef006621.items & IT_SUPER_NAILGUN))
    {
        return IT_SUPER_NAILGUN;
    }
    
    
    if((globaldef006621.ammo_rockets >= TRUE) && (globaldef006621.items & IT_GRENADE_LAUNCHER))
    {
        return IT_GRENADE_LAUNCHER;
    }
    
    
    if((globaldef006621.ammo_shells >= FL_SWIM) && (globaldef006621.items & IT_SUPER_SHOTGUN))
    {
        return IT_SUPER_SHOTGUN;
    }
    
    
    if((globaldef006621.ammo_nails >= TRUE) && (globaldef006621.items & IT_NAILGUN))
    {
        return IT_NAILGUN;
    }
    
    
    if((globaldef006621.ammo_shells >= TRUE) && (globaldef006621.items & IT_SHOTGUN))
    {
        return IT_SHOTGUN;
    }
    
    return IT_AXE;
};


// func002340
// function begins at statement 34819, parm_start=18901
// OP_LOAD_F	18901	162	18903
// OP_BITAND	18903	273	18904
// OP_IFNOT	18904	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18901	181	18905
// OP_LOAD_F	18905	162	18906
// OP_BITAND	18906	273	18907
// OP_IFNOT	18907	2	0
// OP_RETURN	214	0	0
// OP_LOAD_ENT	18901	181	18908
// OP_LOAD_F	18908	162	18909
// OP_BITAND	18909	275	18910
// OP_IFNOT	18910	2	0
// OP_RETURN	214	0	0
// OP_LOAD_F	18901	152	18911
// OP_LT	18911	1536	18912
// OP_IFNOT	18912	2	0
// OP_RETURN	214	0	0
// OP_LOAD_F	18901	162	18913
// OP_BITAND	18913	275	18914
// OP_IFNOT	18914	9	0
// OP_LOAD_F	18901	152	18915
// OP_LOAD_F	18901	188	18916
// OP_LOAD_F	18901	187	18917
// OP_MUL_F	18916	18917	18918
// OP_ADD_F	18915	18918	18919
// OP_GT	18919	1536	18920
// OP_IFNOT	18920	2	0
// OP_RETURN	213	0	0
// OP_LOAD_ENT	18901	181	18921
// OP_STORE_V	18921	4	0
// OP_CALL1	1041	0	0
// OP_STORE_F	1	18902	0
// OP_LOAD_F	18901	154	18922
// OP_ADD_F	260	259	18923
// OP_BITAND	18922	18923	18924
// OP_NOT_F	18924	0	18925
// OP_IFNOT	18925	5	0
// OP_ADD_F	260	259	18926
// OP_BITAND	18902	18926	18927
// OP_IFNOT	18927	2	0
// OP_RETURN	214	0	0
// OP_LOAD_F	18901	154	18928
// OP_ADD_F	260	259	18929
// OP_ADD_F	18929	258	18930
// OP_ADD_F	18930	257	18931
// OP_BITAND	18928	18931	18932
// OP_NOT_F	18932	0	18933
// OP_IFNOT	18933	7	0
// OP_ADD_F	260	259	18934
// OP_ADD_F	18934	258	18935
// OP_ADD_F	18935	257	18936
// OP_BITAND	18902	18936	18937
// OP_IFNOT	18937	2	0
// OP_RETURN	214	0	0
// OP_LOAD_F	18901	154	18938
// OP_BITAND	18938	259	18939
// OP_IFNOT	18939	2	0
// OP_RETURN	213	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006622) func002340 = 
{
    local float globaldef006623;
    
    if(globaldef006622.items & IT_INVULNERABILITY)
    {
        return FALSE;
    }
    
    
    if(globaldef006622.enemy.items & IT_INVULNERABILITY)
    {
        return TRUE;
    }
    
    
    if(globaldef006622.enemy.items & IT_QUAD)
    {
        return TRUE;
    }
    
    
    if(globaldef006622.health < 70)
    {
        return TRUE;
    }
    
    
    if(globaldef006622.items & IT_QUAD)
    {
        
        if((globaldef006622.health + (globaldef006622.armorvalue * globaldef006622.armortype)) > 70)
        {
            return FALSE;
        }
        
    }
    
    globaldef006623 = func002339(globaldef006622.enemy);
    
    if(!(globaldef006622.weapon & (IT_LIGHTNING + IT_ROCKET_LAUNCHER)))
    {
        
        if(globaldef006623 & (IT_LIGHTNING + IT_ROCKET_LAUNCHER))
        {
            return TRUE;
        }
        
    }
    
    
    if(!(globaldef006622.weapon & (((IT_LIGHTNING + IT_ROCKET_LAUNCHER) + IT_GRENADE_LAUNCHER) + IT_SUPER_NAILGUN)))
    {
        
        if(globaldef006623 & (((IT_LIGHTNING + IT_ROCKET_LAUNCHER) + IT_GRENADE_LAUNCHER) + IT_SUPER_NAILGUN))
        {
            return TRUE;
        }
        
    }
    
    
    if(globaldef006622.weapon & IT_ROCKET_LAUNCHER)
    {
        return FALSE;
    }
    
    return FALSE;
};


// func002341
// function begins at statement 34880, parm_start=18940
// OP_STORE_V	18940	4	0
// OP_CALL1	1042	0	0
// OP_NOT_F	1	0	18941
// OP_RETURN	18941	0	0
// OP_DONE	0	0	0
float (entity globaldef006624) func002341 = 
{
    return !func002340(globaldef006624);
};


// func002342
// function begins at statement 34885, parm_start=18942
// OP_LOAD_ENT	18942	181	18943
// OP_LOAD_F	18943	162	18944
// OP_BITAND	18944	272	18945
// OP_IFNOT	18945	5	0
// OP_LOAD_F	18942	588	18946
// OP_LT	18946	228	18947
// OP_IFNOT	18947	2	0
// OP_RETURN	214	0	0
// OP_RETURN	213	0	0
// OP_DONE	0	0	0
float (entity globaldef006625) func002342 = 
{
    
    if(globaldef006625.enemy.items & IT_INVISIBILITY)
    {
        
        if(globaldef006625.field000265 < MOVETYPE_WALK)
        {
            return TRUE;
        }
        
    }
    
    return FALSE;
};


// func002343
// function begins at statement 34895, parm_start=18949
// OP_LOAD_ENT	18950	201	18959
// OP_STORE_ENT	18959	18951	0
// OP_STORE_ENT	18959	18952	0
// OP_IFNOT	18952	6	0
// OP_LOAD_V	18952	94	18960
// OP_STORE_V	18960	18953	0
// OP_LOAD_V	18952	98	18963
// OP_STORE_V	18963	18956	0
// OP_GOTO	3	0	0
// OP_STORE_V	286	18956	0
// OP_STORE_V	286	18953	0
// OP_NE_V	18953	18956	18966
// OP_IFNOT	18966	42	0
// OP_LOAD_F	18952	438	18967
// OP_NE_F	18967	283	18968
// OP_IFNOT	18968	2	0
// OP_RETURN	0	0	0
// OP_LOAD_F	18951	95	18969
// OP_LT	18969	18953	18970
// OP_IFNOT	18970	3	0
// OP_LOAD_F	18951	95	18971
// OP_STORE_F	18971	18953	0
// OP_LOAD_F	18951	99	18972
// OP_GT	18972	18956	18973
// OP_IFNOT	18973	3	0
// OP_LOAD_F	18951	99	18974
// OP_STORE_F	18974	18956	0
// OP_LOAD_F	18951	96	18975
// OP_LT	18975	18954	18976
// OP_IFNOT	18976	3	0
// OP_LOAD_F	18951	96	18977
// OP_STORE_F	18977	18954	0
// OP_LOAD_F	18951	100	18978
// OP_GT	18978	18957	18979
// OP_IFNOT	18979	3	0
// OP_LOAD_F	18951	100	18980
// OP_STORE_F	18980	18957	0
// OP_LOAD_F	18951	97	18981
// OP_LT	18981	18955	18982
// OP_IFNOT	18982	3	0
// OP_LOAD_F	18951	97	18983
// OP_STORE_F	18983	18955	0
// OP_LOAD_F	18951	101	18984
// OP_GT	18984	18958	18985
// OP_IFNOT	18985	3	0
// OP_LOAD_F	18951	101	18986
// OP_STORE_F	18986	18958	0
// OP_LOAD_ENT	18951	181	18987
// OP_STORE_ENT	18987	18951	0
// OP_NE_E	18951	18952	18988
// OP_NE_E	18951	30	18989
// OP_AND	18988	18989	18990
// OP_IF	18990	-35	0
// OP_GOTO	2	0	0
// OP_RETURN	0	0	0
// OP_STORE_F	213	18993	0
// OP_STORE_F	213	18992	0
// OP_STORE_F	213	18991	0
// OP_STORE_F	213	18994	0
// OP_LOAD_V	18949	105	19003
// OP_STORE_V	19003	18999	0
// OP_ADD_F	18953	213	19006
// OP_LOAD_F	18949	95	19007
// OP_LT	19006	19007	19008
// OP_LOAD_F	18949	99	19009
// OP_SUB_F	18956	213	19010
// OP_LT	19009	19010	19011
// OP_AND	19008	19011	19012
// OP_IFNOT	19012	2	0
// OP_STORE_F	214	18991	0
// OP_ADD_F	18954	213	19013
// OP_LOAD_F	18949	96	19014
// OP_LT	19013	19014	19015
// OP_LOAD_F	18949	100	19016
// OP_SUB_F	18957	213	19017
// OP_LT	19016	19017	19018
// OP_AND	19015	19018	19019
// OP_IFNOT	19019	2	0
// OP_STORE_F	214	18992	0
// OP_ADD_F	18955	213	19020
// OP_LOAD_F	18949	97	19021
// OP_LT	19020	19021	19022
// OP_LOAD_F	18949	101	19023
// OP_SUB_F	18958	213	19024
// OP_LT	19023	19024	19025
// OP_AND	19022	19025	19026
// OP_IFNOT	19026	2	0
// OP_STORE_F	214	18993	0
// OP_AND	18991	18992	19027
// OP_IFNOT	19027	14	0
// OP_LT	19001	18955	19028
// OP_IFNOT	19028	5	0
// OP_STORE_V	2967	18996	0
// OP_ADD_F	18958	305	19029
// OP_STORE_F	19029	19001	0
// OP_GOTO	6	0	0
// OP_GT	19001	18958	19030
// OP_IFNOT	19030	4	0
// OP_STORE_V	2980	18996	0
// OP_SUB_F	18955	305	19031
// OP_STORE_F	19031	19001	0
// OP_STORE_F	214	18994	0
// OP_GOTO	30	0	0
// OP_AND	18991	18993	19032
// OP_IFNOT	19032	14	0
// OP_LT	19000	18954	19033
// OP_IFNOT	19033	5	0
// OP_STORE_V	10055	18996	0
// OP_ADD_F	18957	305	19034
// OP_STORE_F	19034	19000	0
// OP_GOTO	6	0	0
// OP_GT	19000	18957	19035
// OP_IFNOT	19035	4	0
// OP_STORE_V	2960	18996	0
// OP_SUB_F	18954	305	19036
// OP_STORE_F	19036	19000	0
// OP_STORE_F	214	18994	0
// OP_GOTO	15	0	0
// OP_AND	18992	18993	19037
// OP_IFNOT	19037	13	0
// OP_LT	18999	18953	19038
// OP_IFNOT	19038	5	0
// OP_STORE_V	19039	18996	0
// OP_ADD_F	18956	305	19042
// OP_STORE_F	19042	18999	0
// OP_GOTO	6	0	0
// OP_GT	18999	18956	19043
// OP_IFNOT	19043	4	0
// OP_STORE_V	19044	18996	0
// OP_SUB_F	18953	305	19047
// OP_STORE_F	19047	18999	0
// OP_STORE_F	214	18994	0
// OP_IFNOT	18994	25	0
// OP_LOAD_V	18949	113	19051
// OP_STORE_V	19051	4	0
// OP_CALL1	459	0	0
// OP_STORE_V	1	19048	0
// OP_MUL_V	18996	19048	19054
// OP_LT	19054	539	19055
// OP_IFNOT	19055	2	0
// OP_RETURN	0	0	0
// OP_STORE_ENT	28	19002	0
// OP_STORE_ENT	18949	28	0
// OP_STORE_F	213	18995	0
// OP_STORE_V	28	4	0
// OP_STORE_V	18999	7	0
// OP_CALL2	453	0	0
// OP_ADD_F	19001	217	19056
// OP_STORE_F	19056	19001	0
// OP_ADD_F	18995	214	19057
// OP_STORE_F	19057	18995	0
// OP_CALL0	481	0	0
// OP_NOT_F	1	0	19058
// OP_LT	18995	235	19059
// OP_AND	19058	19059	19060
// OP_IF	19060	-11	0
// OP_STORE_ENT	19002	28	0
// OP_DONE	0	0	0
void (entity globaldef006627, entity globaldef006628) func002343 = 
{
    local entity globaldef006629;
    local entity globaldef006630;
    local vector globaldef006631;
    local vector globaldef006635;
    local float globaldef006639;
    local float globaldef006640;
    local float globaldef006641;
    local float globaldef006642;
    local float globaldef006643;
    local vector globaldef006644;
    local vector globaldef006648;
    local entity globaldef006652;
    local vector globaldef006653;
    local vector globaldef006654;
    local vector globaldef006655;
    globaldef006630 = globaldef006629 = globaldef006628.owner;
    if(globaldef006630)
    {
        globaldef006631 = globaldef006630.absmin;
        globaldef006635 = globaldef006630.absmax;
    }
    else
    {
        globaldef006635 = VEC_ORIGIN;
        globaldef006631 = VEC_ORIGIN;
    }
    
    if(globaldef006631 != globaldef006635)
    {
        
        if(globaldef006630.state != STATE_BOTTOM)
        {
            return;
        }
        
        do
        {
            
            if(globaldef006629.absmin_x < globaldef006631_x)
            {
                globaldef006631_x = globaldef006629.absmin_x;
            }
            
            
            if(globaldef006629.absmax_x > globaldef006635_x)
            {
                globaldef006635_x = globaldef006629.absmax_x;
            }
            
            
            if(globaldef006629.absmin_y < globaldef006631_y)
            {
                globaldef006631_y = globaldef006629.absmin_y;
            }
            
            
            if(globaldef006629.absmax_y > globaldef006635_y)
            {
                globaldef006635_y = globaldef006629.absmax_y;
            }
            
            
            if(globaldef006629.absmin_z < globaldef006631_z)
            {
                globaldef006631_z = globaldef006629.absmin_z;
            }
            
            
            if(globaldef006629.absmax_z > globaldef006635_z)
            {
                globaldef006635_z = globaldef006629.absmax_z;
            }
            
            globaldef006629 = globaldef006629.enemy;
        } while ((globaldef006629 != globaldef006630) && (globaldef006629 != world));
    }
    else
    {
        return;
    }
    
    globaldef006641 = FALSE;
    globaldef006640 = FALSE;
    globaldef006639 = FALSE;
    globaldef006642 = FALSE;
    globaldef006648 = globaldef006627.origin;
    
    if(((globaldef006631_x + FALSE) < globaldef006627.absmin_x) && (globaldef006627.absmax_x < (globaldef006635_x - FALSE)))
    {
        globaldef006639 = TRUE;
    }
    
    
    if(((globaldef006631_y + FALSE) < globaldef006627.absmin_y) && (globaldef006627.absmax_y < (globaldef006635_y - FALSE)))
    {
        globaldef006640 = TRUE;
    }
    
    
    if(((globaldef006631_z + FALSE) < globaldef006627.absmin_z) && (globaldef006627.absmax_z < (globaldef006635_z - FALSE)))
    {
        globaldef006641 = TRUE;
    }
    
    if(globaldef006639 && globaldef006640)
    {
        if(globaldef006648_z < globaldef006631_z)
        {
            globaldef006644 = '0 0 1';
            globaldef006648_z = globaldef006635_z + SVC_SIGNONNUM;
        }
        else
        {
            
            if(globaldef006648_z > globaldef006635_z)
            {
                globaldef006644 = '0 0 -1';
                globaldef006648_z = globaldef006631_z - SVC_SIGNONNUM;
            }
            
        }
        
        globaldef006642 = TRUE;
    }
    else
    {
        if(globaldef006639 && globaldef006641)
        {
            if(globaldef006648_y < globaldef006631_y)
            {
                globaldef006644 = '0 1 0';
                globaldef006648_y = globaldef006635_y + SVC_SIGNONNUM;
            }
            else
            {
                
                if(globaldef006648_y > globaldef006635_y)
                {
                    globaldef006644 = '0 -1 0';
                    globaldef006648_y = globaldef006631_y - SVC_SIGNONNUM;
                }
                
            }
            
            globaldef006642 = TRUE;
        }
        else
        {
            
            if(globaldef006640 && globaldef006641)
            {
                if(globaldef006648_x < globaldef006631_x)
                {
                    globaldef006644 = globaldef006653;
                    globaldef006648_x = globaldef006635_x + SVC_SIGNONNUM;
                }
                else
                {
                    
                    if(globaldef006648_x > globaldef006635_x)
                    {
                        globaldef006644 = globaldef006654;
                        globaldef006648_x = globaldef006631_x - SVC_SIGNONNUM;
                    }
                    
                }
                
                globaldef006642 = TRUE;
            }
            
        }
        
    }
    
    
    if(globaldef006642)
    {
        globaldef006655 = normalize(globaldef006627.velocity);
        
        if((globaldef006644 * globaldef006655) < RA_PLAYERSTATTIME)
        {
            return;
        }
        
        globaldef006652 = self;
        self = globaldef006627;
        globaldef006643 = FALSE;
        do
        {
            setorigin(self, globaldef006648);
            globaldef006648_z = globaldef006648_z + FL_CLIENT;
            globaldef006643 = globaldef006643 + TRUE;
        } while (!droptofloor() && (globaldef006643 < MOVETYPE_BOUNCE));
        self = globaldef006652;
    }
    
};


// func002344
// function begins at statement 35053, parm_start=19062
// OP_LOAD_V	19063	98	19071
// OP_LOAD_V	19063	94	19074
// OP_ADD_V	19071	19074	19077
// OP_MUL_VF	19077	539	19080
// OP_LOAD_V	19062	105	19083
// OP_SUB_V	19080	19083	19086
// OP_STORE_V	19086	19065	0
// OP_STORE_V	19065	4	0
// OP_CALL1	459	0	0
// OP_LOAD_V	19062	113	19089
// OP_STORE_V	19089	19068	0
// OP_STORE_V	19068	4	0
// OP_CALL1	459	0	0
// OP_MUL_V	19065	19068	19092
// OP_LE	19092	3036	19093
// OP_IFNOT	19093	2	0
// OP_RETURN	0	0	0
// OP_STORE_V	30	4	0
// OP_STORE_V	197	7	0
// OP_LOAD_S	19063	196	19094
// OP_STORE_V	19094	10	0
// OP_CALL3	468	0	0
// OP_STORE_ENT	1	19064	0
// OP_NOT_ENT	19064	0	19095
// OP_IFNOT	19095	4	0
// OP_STORE_V	11254	4	0
// OP_CALL1	473	0	0
// OP_RETURN	0	0	0
// OP_LOAD_V	19064	400	19096
// OP_STORE_V	19096	4	0
// OP_CALL1	452	0	0
// OP_STORE_V	19062	4	0
// OP_LOAD_V	19064	105	19099
// OP_STORE_V	19099	7	0
// OP_CALL2	453	0	0
// OP_ADDRESS	19062	117	19102
// OP_LOAD_V	19064	400	19105
// OP_STOREP_V	19105	19102	0
// OP_ADDRESS	19062	174	19108
// OP_STOREP_F	214	19108	0
// OP_ADDRESS	19062	186	19109
// OP_ADD_F	31	5599	19110
// OP_STOREP_F	19110	19109	0
// OP_ADDRESS	19062	113	19111
// OP_MUL_VF	59	540	19114
// OP_STOREP_V	19114	19111	0
// OP_DONE	0	0	0
void (entity globaldef006660, entity globaldef006661) func002344 = 
{
    local entity globaldef006662;
    local vector globaldef006663;
    local vector globaldef006667;
    globaldef006663 = ((globaldef006661.absmax + globaldef006661.absmin) * RA_PLAYERSTATTIME) - globaldef006660.origin;
    normalize(globaldef006663);
    globaldef006667 = globaldef006660.velocity;
    normalize(globaldef006667);
    
    if((globaldef006663 * globaldef006667) <= 0.1)
    {
        return;
    }
    
    globaldef006662 = find(world, targetname, globaldef006661.target);
    
    if(!globaldef006662)
    {
        dprint("couldn't find teleporter target\n");
        return;
    }
    
    makevectors(globaldef006662.mangle);
    setorigin(globaldef006660, globaldef006662.origin);
    globaldef006660.angles = globaldef006662.mangle;
    globaldef006660.fixangle = TRUE;
    globaldef006660.teleport_time = time + 0.7;
    globaldef006660.velocity = v_forward * RA_MAXIDLETIME;
};


// func002345
// function begins at statement 35100, parm_start=19118
// OP_LOAD_V	19118	105	19120
// OP_STORE_V	19120	4	0
// OP_STORE_V	9173	7	0
// OP_CALL2	471	0	0
// OP_STORE_ENT	1	19119	0
// OP_IFNOT	19119	18	0
// OP_LOAD_S	19119	129	19123
// OP_EQ_S	19123	5259	19124
// OP_IFNOT	19124	5	0
// OP_STORE_V	19118	4	0
// OP_STORE_V	19119	7	0
// OP_CALL2	18948	0	0
// OP_RETURN	0	0	0
// OP_LOAD_S	19119	129	19125
// OP_EQ_S	19125	19126	19127
// OP_IFNOT	19127	5	0
// OP_STORE_V	19118	4	0
// OP_STORE_V	19119	7	0
// OP_CALL2	19061	0	0
// OP_RETURN	0	0	0
// OP_LOAD_ENT	19119	164	19128
// OP_STORE_ENT	19128	19119	0
// OP_GOTO	-17	0	0
// OP_DONE	0	0	0
void (entity globaldef006672) func002345 = 
{
    local entity globaldef006673;
    globaldef006673 = findradius(globaldef006672.origin, 75);
    
    while(globaldef006673)
    {
        
        if(globaldef006673.classname == "door")
        {
            func002343(globaldef006672, globaldef006673);
            return;
        }
        
        
        if(globaldef006673.classname == "trigger_teleport")
        {
            func002344(globaldef006672, globaldef006673);
            return;
        }
        
        globaldef006673 = globaldef006673.chain;
    }
    
};


// func002346
// function begins at statement 35124, parm_start=19130
// OP_STORE_ENT	19130	81	0
// OP_STORE_V	343	4	0
// OP_STORE_V	306	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	235	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	2137	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19131	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19132	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19133	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19131	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19134	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19135	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	219	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19136	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19137	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19138	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19139	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	14538	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	219	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_LOAD_ENT	19130	667	19140
// OP_LOAD_S	19140	180	19141
// OP_STORE_V	19141	7	0
// OP_CALL2	502	0	0
// OP_DONE	0	0	0
void (entity globaldef006676) func002346 = 
{
    msg_entity = globaldef006676;
    WriteByte(MSG_ONE, SVC_CENTERPRINT);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, MOVETYPE_BOUNCE);
    WriteByte(MSG_ONE, 214);
    WriteByte(MSG_ONE, 233);
    WriteByte(MSG_ONE, 229);
    WriteByte(MSG_ONE, 247);
    WriteByte(MSG_ONE, 233);
    WriteByte(MSG_ONE, 238);
    WriteByte(MSG_ONE, 231);
    WriteByte(MSG_ONE, FL_MONSTER);
    WriteByte(MSG_ONE, 230);
    WriteByte(MSG_ONE, 242);
    WriteByte(MSG_ONE, 239);
    WriteByte(MSG_ONE, 237);
    WriteByte(MSG_ONE, 186);
    WriteByte(MSG_ONE, FL_MONSTER);
    WriteString(MSG_ONE, globaldef006676.field000344.netname);
};


// func002347
// function begins at statement 35212, parm_start=19143
// OP_ADDRESS	19143	162	19144
// OP_LOAD_ENT	19143	667	19145
// OP_LOAD_F	19145	162	19146
// OP_STOREP_F	19146	19144	0
// OP_ADDRESS	19143	158	19147
// OP_LOAD_ENT	19143	667	19148
// OP_LOAD_F	19148	158	19149
// OP_STOREP_F	19149	19147	0
// OP_ADDRESS	19143	159	19150
// OP_LOAD_ENT	19143	667	19151
// OP_LOAD_F	19151	159	19152
// OP_STOREP_F	19152	19150	0
// OP_ADDRESS	19143	160	19153
// OP_LOAD_ENT	19143	667	19154
// OP_LOAD_F	19154	160	19155
// OP_STOREP_F	19155	19153	0
// OP_ADDRESS	19143	161	19156
// OP_LOAD_ENT	19143	667	19157
// OP_LOAD_F	19157	161	19158
// OP_STOREP_F	19158	19156	0
// OP_ADDRESS	19143	157	19159
// OP_LOAD_ENT	19143	667	19160
// OP_LOAD_F	19160	157	19161
// OP_STOREP_F	19161	19159	0
// OP_ADDRESS	19143	188	19162
// OP_LOAD_ENT	19143	667	19163
// OP_LOAD_F	19163	188	19164
// OP_STOREP_F	19164	19162	0
// OP_LOAD_F	19143	152	19165
// OP_GT	19165	1997	19166
// OP_IFNOT	19166	3	0
// OP_ADDRESS	19143	152	19167
// OP_STOREP_F	1997	19167	0
// OP_LOAD_F	19143	152	19168
// OP_LOAD_ENT	19143	667	19169
// OP_LOAD_F	19169	152	19170
// OP_GT	19168	19170	19171
// OP_IFNOT	19171	9	0
// OP_ADDRESS	19143	198	19172
// OP_LOAD_F	19143	198	19173
// OP_LOAD_F	19143	152	19174
// OP_LOAD_ENT	19143	667	19175
// OP_LOAD_F	19175	152	19176
// OP_SUB_F	19174	19176	19177
// OP_ADD_F	19173	19177	19178
// OP_STOREP_F	19178	19172	0
// OP_ADDRESS	19143	152	19179
// OP_LOAD_ENT	19143	667	19180
// OP_LOAD_F	19180	152	19181
// OP_STOREP_F	19181	19179	0
// OP_ADDRESS	19143	155	19182
// OP_LOAD_ENT	19143	667	19183
// OP_LOAD_S	19183	155	19184
// OP_STOREP_S	19184	19182	0
// OP_ADDRESS	19143	156	19185
// OP_LOAD_ENT	19143	667	19186
// OP_LOAD_F	19186	156	19187
// OP_STOREP_F	19187	19185	0
// OP_DONE	0	0	0
void (entity globaldef006687) func002347 = 
{
    globaldef006687.items = globaldef006687.field000344.items;
    globaldef006687.ammo_shells = globaldef006687.field000344.ammo_shells;
    globaldef006687.ammo_nails = globaldef006687.field000344.ammo_nails;
    globaldef006687.ammo_rockets = globaldef006687.field000344.ammo_rockets;
    globaldef006687.ammo_cells = globaldef006687.field000344.ammo_cells;
    globaldef006687.currentammo = globaldef006687.field000344.currentammo;
    globaldef006687.armorvalue = globaldef006687.field000344.armorvalue;
    
    if(globaldef006687.health > 100)
    {
        globaldef006687.health = 100;
    }
    
    
    if(globaldef006687.health > globaldef006687.field000344.health)
    {
        globaldef006687.dmg_take = globaldef006687.dmg_take + (globaldef006687.health - globaldef006687.field000344.health);
    }
    
    globaldef006687.health = globaldef006687.field000344.health;
    globaldef006687.weaponmodel = globaldef006687.field000344.weaponmodel;
    globaldef006687.weaponframe = globaldef006687.field000344.weaponframe;
};


// func002348
// function begins at statement 35271, parm_start=19189
// OP_ADDRESS	19189	162	19190
// OP_STOREP_F	213	19190	0
// OP_ADDRESS	19189	158	19191
// OP_STOREP_F	213	19191	0
// OP_ADDRESS	19189	159	19192
// OP_STOREP_F	213	19192	0
// OP_ADDRESS	19189	160	19193
// OP_STOREP_F	213	19193	0
// OP_ADDRESS	19189	161	19194
// OP_STOREP_F	213	19194	0
// OP_ADDRESS	19189	157	19195
// OP_STOREP_F	9989	19195	0
// OP_ADDRESS	19189	188	19196
// OP_STOREP_F	9989	19196	0
// OP_ADDRESS	19189	152	19197
// OP_STOREP_F	9989	19197	0
// OP_ADDRESS	19189	155	19198
// OP_STOREP_S	3002	19198	0
// OP_DONE	0	0	0
void (entity globaldef006689) func002348 = 
{
    globaldef006689.items = FALSE;
    globaldef006689.ammo_shells = FALSE;
    globaldef006689.ammo_nails = FALSE;
    globaldef006689.ammo_rockets = FALSE;
    globaldef006689.ammo_cells = FALSE;
    globaldef006689.currentammo = 99;
    globaldef006689.armorvalue = 99;
    globaldef006689.health = 99;
    globaldef006689.weaponmodel = "";
};


// func002349
// function begins at statement 35290, parm_start=19199
// OP_STORE_ENT	19199	81	0
// OP_STORE_V	343	4	0
// OP_STORE_V	301	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19200	7	0
// OP_CALL2	503	0	0
// OP_DONE	0	0	0
void (entity globaldef006690, entity globaldef006691) func002349 = 
{
    msg_entity = globaldef006690;
    WriteByte(MSG_ONE, SVC_SETVIEW);
    WriteEntity(MSG_ONE, globaldef006691);
};


// func002350
// function begins at statement 35298, parm_start=19201
// OP_STORE_ENT	19201	81	0
// OP_STORE_V	343	4	0
// OP_STORE_V	303	7	0
// OP_CALL2	496	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19202	7	0
// OP_CALL2	501	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19203	7	0
// OP_CALL2	501	0	0
// OP_STORE_V	343	4	0
// OP_STORE_V	19204	7	0
// OP_CALL2	501	0	0
// OP_DONE	0	0	0
void (entity globaldef006692, vector globaldef006693) func002350 = 
{
    msg_entity = globaldef006692;
    WriteByte(MSG_ONE, SVC_SETANGLE);
    WriteAngle(MSG_ONE, globaldef006693_x);
    WriteAngle(MSG_ONE, globaldef006693_y);
    WriteAngle(MSG_ONE, globaldef006693_z);
};


// func002351
// function begins at statement 35312, parm_start=19206
// OP_STORE_V	19206	4	0
// OP_CALL1	3179	0	0
// OP_STORE_F	1	19206	0
// OP_STORE_V	19207	4	0
// OP_CALL1	3179	0	0
// OP_STORE_F	1	19207	0
// OP_GT	19208	3036	19210
// OP_IFNOT	19210	2	0
// OP_STORE_F	3036	19208	0
// OP_LT	19208	213	19211
// OP_IFNOT	19211	2	0
// OP_STORE_F	213	19208	0
// OP_GT	19206	19207	19212
// OP_IFNOT	19212	17	0
// OP_SUB_F	19206	19207	19213
// OP_LT	19213	1296	19214
// OP_IFNOT	19214	7	0
// OP_SUB_F	19207	19206	19215
// OP_STORE_F	19215	19209	0
// OP_MUL_F	19209	235	19216
// OP_MUL_F	19216	19208	19217
// OP_RETURN	19217	0	0
// OP_GOTO	7	0	0
// OP_SUB_F	1298	19206	19218
// OP_ADD_F	19218	19207	19219
// OP_STORE_F	19219	19209	0
// OP_MUL_F	19209	235	19220
// OP_MUL_F	19220	19208	19221
// OP_RETURN	19221	0	0
// OP_GOTO	16	0	0
// OP_SUB_F	19207	19206	19222
// OP_LT	19222	1296	19223
// OP_IFNOT	19223	7	0
// OP_SUB_F	19207	19206	19224
// OP_STORE_F	19224	19209	0
// OP_MUL_F	19209	235	19225
// OP_MUL_F	19225	19208	19226
// OP_RETURN	19226	0	0
// OP_GOTO	7	0	0
// OP_ADD_F	7001	19207	19227
// OP_SUB_F	19227	19206	19228
// OP_STORE_F	19228	19209	0
// OP_MUL_F	19209	235	19229
// OP_MUL_F	19229	19208	19230
// OP_RETURN	19230	0	0
// OP_DONE	0	0	0
float (float globaldef006698, float globaldef006699, float globaldef006700) func002351 = 
{
    local float globaldef006701;
    globaldef006698 = anglemod(globaldef006698);
    globaldef006699 = anglemod(globaldef006699);
    
    if(globaldef006700 > 0.1)
    {
        globaldef006700 = 0.1;
    }
    
    
    if(globaldef006700 < FALSE)
    {
        globaldef006700 = FALSE;
    }
    
    if(globaldef006698 > globaldef006699)
    {
        if((globaldef006698 - globaldef006699) < 180)
        {
            globaldef006701 = globaldef006699 - globaldef006698;
            return (globaldef006701 * MOVETYPE_BOUNCE) * globaldef006700;
        }
        else
        {
            globaldef006701 = (360 - globaldef006698) + globaldef006699;
            return (globaldef006701 * MOVETYPE_BOUNCE) * globaldef006700;
        }
        
    }
    else
    {
        if((globaldef006699 - globaldef006698) < 180)
        {
            globaldef006701 = globaldef006699 - globaldef006698;
            return (globaldef006701 * MOVETYPE_BOUNCE) * globaldef006700;
        }
        else
        {
            globaldef006701 = (-360 + globaldef006699) - globaldef006698;
            return (globaldef006701 * MOVETYPE_BOUNCE) * globaldef006700;
        }
        
    }
    
};


// func002352
// function begins at statement 35358, parm_start=19232
// OP_SUB_F	31	19238	19243
// OP_STORE_F	19243	19242	0
// OP_STORE_V	19232	4	0
// OP_STORE_V	19235	7	0
// OP_STORE_V	19242	10	0
// OP_CALL3	19205	0	0
// OP_STORE_F	1	19239	0
// OP_STORE_V	19233	4	0
// OP_STORE_V	19236	7	0
// OP_STORE_V	19242	10	0
// OP_CALL3	19205	0	0
// OP_STORE_F	1	19240	0
// OP_STORE_V	19234	4	0
// OP_STORE_V	19237	7	0
// OP_STORE_V	19242	10	0
// OP_CALL3	19205	0	0
// OP_STORE_F	1	19241	0
// OP_ADD_V	19232	19239	19244
// OP_RETURN	19244	0	0
// OP_DONE	0	0	0
vector (vector globaldef006703, vector globaldef006707, float globaldef006711) func002352 = 
{
    local vector globaldef006712;
    local float globaldef006716;
    globaldef006716 = time - globaldef006711;
    globaldef006712_x = func002351(globaldef006703_x, globaldef006707_x, globaldef006716);
    globaldef006712_y = func002351(globaldef006703_y, globaldef006707_y, globaldef006716);
    globaldef006712_z = func002351(globaldef006703_z, globaldef006707_z, globaldef006716);
    return globaldef006703 + globaldef006712;
};


// func002353
// function begins at statement 35378, parm_start=19248
// OP_ADDRESS	19248	182	19266
// OP_LOAD_F	19248	182	19267
// OP_BITOR	19267	223	19268
// OP_STOREP_F	19268	19266	0
// OP_LOAD_F	19248	116	19269
// OP_STORE_F	19269	19256	0
// OP_ADDRESS	19248	116	19270
// OP_STOREP_F	213	19270	0
// OP_STORE_F	59	19257	0
// OP_STORE_F	60	19258	0
// OP_STORE_F	213	19259	0
// OP_STORE_V	19257	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	19249	0
// OP_IFNOT	19249	4	0
// OP_DIV_F	214	19249	19271
// OP_STORE_F	19271	19249	0
// OP_GOTO	2	0	0
// OP_STORE_F	213	19249	0
// OP_MUL_VF	19257	19249	19272
// OP_STORE_V	19272	19257	0
// OP_LOAD_V	19248	113	19275
// OP_MUL_V	19257	19275	19278
// OP_STORE_F	19278	19255	0
// OP_MUL_FV	19255	19257	19279
// OP_STORE_V	19279	19260	0
// OP_STORE_V	19260	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	19251	0
// OP_LT	19255	213	19282
// OP_IFNOT	19282	3	0
// OP_MUL_F	19251	276	19283
// OP_STORE_F	19283	19251	0
// OP_LOAD_V	19248	113	19284
// OP_SUB_V	19284	19260	19287
// OP_STORE_V	19287	19263	0
// OP_MUL_F	19251	19249	19290
// OP_MUL_VF	59	19290	19291
// OP_STORE_V	19291	19260	0
// OP_ADD_F	19262	19256	19294
// OP_STORE_F	19294	19262	0
// OP_STORE_V	19260	4	0
// OP_CALL1	462	0	0
// OP_STORE_F	1	19251	0
// OP_MUL_V	59	2967	19296
// OP_MUL_F	1997	19296	19297
// OP_SUB_F	19295	19297	19298
// OP_STORE_F	19298	19252	0
// OP_GT	19251	19252	19299
// OP_IFNOT	19299	4	0
// OP_DIV_F	19252	19251	19300
// OP_MUL_VF	19260	19300	19301
// OP_STORE_V	19301	19260	0
// OP_ADDRESS	19248	113	19304
// OP_ADD_V	19260	19263	19307
// OP_STOREP_V	19307	19304	0
// OP_DONE	0	0	0
void (entity globaldef006718) func002353 = 
{
    local float globaldef006719;
    local float globaldef006720;
    local float globaldef006721;
    local float globaldef006722;
    local float globaldef006723;
    local float globaldef006724;
    local float globaldef006725;
    local float globaldef006726;
    local vector globaldef006727;
    local vector globaldef006731;
    local vector globaldef006735;
    globaldef006718.flags = globaldef006718.flags | FL_ONGROUND;
    globaldef006726 = globaldef006718.velocity_z;
    globaldef006718.velocity_z = FALSE;
    globaldef006727_x = v_forward_x;
    globaldef006727_y = v_forward_y;
    globaldef006727_z = FALSE;
    globaldef006719 = vlen(globaldef006727);
    if(globaldef006719)
    {
        globaldef006719 = TRUE / globaldef006719;
    }
    else
    {
        globaldef006719 = FALSE;
    }
    
    globaldef006727 = globaldef006727 * globaldef006719;
    globaldef006725 = globaldef006727 * globaldef006718.velocity;
    globaldef006731 = globaldef006725 * globaldef006727;
    globaldef006721 = vlen(globaldef006731);
    
    if(globaldef006725 < FALSE)
    {
        globaldef006721 = globaldef006721 * CONTENT_EMPTY;
    }
    
    globaldef006735 = globaldef006718.velocity - globaldef006731;
    globaldef006731 = v_forward * (globaldef006721 * globaldef006719);
    globaldef006731_z = globaldef006731_z + globaldef006726;
    globaldef006721 = vlen(globaldef006731);
    globaldef006722 = 320 - (100 * (v_forward * '0 0 1'));
    
    if(globaldef006721 > globaldef006722)
    {
        globaldef006731 = globaldef006731 * (globaldef006722 / globaldef006721);
    }
    
    globaldef006718.velocity = globaldef006731 + globaldef006735;
};


// func002354
// function begins at statement 35435, parm_start=19311
// OP_ADDRESS	19311	93	19316
// OP_STOREP_F	213	19316	0
// OP_ADDRESS	19311	117	19317
// OP_LOAD_ENT	19311	667	19320
// OP_LOAD_V	19320	117	19321
// OP_STOREP_V	19321	19317	0
// OP_LOAD_ENT	19311	667	19324
// OP_LOAD_S	19324	129	19325
// OP_EQ_S	19325	1241	19326
// OP_IFNOT	19326	13	0
// OP_LOAD_V	19311	175	19327
// OP_STORE_V	19327	4	0
// OP_LOAD_ENT	19311	667	19330
// OP_LOAD_V	19330	175	19331
// OP_STORE_V	19331	7	0
// OP_LOAD_F	19311	680	19334
// OP_STORE_V	19334	10	0
// OP_CALL3	19231	0	0
// OP_STORE_V	1	19312	0
// OP_ADDRESS	19311	680	19335
// OP_STOREP_F	31	19335	0
// OP_GOTO	4	0	0
// OP_LOAD_ENT	19311	667	19336
// OP_LOAD_V	19336	175	19337
// OP_STORE_V	19337	19312	0
// OP_STORE_V	19311	4	0
// OP_LOAD_ENT	19311	667	19340
// OP_LOAD_V	19340	105	19341
// OP_STORE_V	19341	7	0
// OP_CALL2	453	0	0
// OP_ADDRESS	19311	166	19344
// OP_LOAD_ENT	19311	667	19347
// OP_LOAD_V	19347	166	19348
// OP_STOREP_V	19348	19344	0
// OP_LOAD_ENT	19311	667	19352
// OP_LOAD_S	19352	129	19353
// OP_EQ_S	19353	1241	19354
// OP_BITAND	821	777	19355
// OP_AND	19354	19355	19356
// OP_IFNOT	19356	7	0
// OP_LOAD_ENT	19311	667	19357
// OP_LOAD_F	19357	608	19358
// OP_STORE_V	19358	4	0
// OP_CALL1	1054	0	0
// OP_STORE_ENT	1	19351	0
// OP_GOTO	3	0	0
// OP_LOAD_ENT	19311	667	19359
// OP_STORE_ENT	19359	19351	0
// OP_STORE_V	19311	4	0
// OP_STORE_V	19351	7	0
// OP_CALL2	1059	0	0
// OP_STORE_V	19311	4	0
// OP_STORE_V	19312	7	0
// OP_CALL2	1060	0	0
// OP_DONE	0	0	0
void (entity globaldef006741) func002354 = 
{
    local vector globaldef006742;
    local float globaldef006746;
    local entity globaldef006747;
    globaldef006741.modelindex = FALSE;
    globaldef006741.angles = globaldef006741.field000344.angles;
    if(globaldef006741.field000344.classname == "bot")
    {
        globaldef006742 = func002352(globaldef006741.v_angle, globaldef006741.field000344.v_angle, globaldef006741.field000357);
        globaldef006741.field000357 = time;
    }
    else
    {
        globaldef006742 = globaldef006741.field000344.v_angle;
    }
    
    setorigin(globaldef006741, globaldef006741.field000344.origin);
    globaldef006741.view_ofs = globaldef006741.field000344.view_ofs;
    if((globaldef006741.field000344.classname == "bot") && (globaldef000804 & globaldef000760))
    {
        globaldef006747 = func002266(globaldef006741.field000344.clientnumber);
    }
    else
    {
        globaldef006747 = globaldef006741.field000344;
    }
    
    func002349(globaldef006741, globaldef006747);
    func002350(globaldef006741, globaldef006742);
};


// func002355
// function begins at statement 35490, parm_start=19361
// OP_LOAD_ENT	19361	667	19384
// OP_LOAD_V	19384	175	19385
// OP_STORE_V	19385	19362	0
// OP_LOAD_ENT	19361	667	19388
// OP_LOAD_S	19388	129	19389
// OP_EQ_S	19389	1241	19390
// OP_IFNOT	19390	12	0
// OP_LOAD_V	19361	668	19391
// OP_STORE_V	19391	4	0
// OP_STORE_V	19362	7	0
// OP_LOAD_F	19361	680	19394
// OP_STORE_V	19394	10	0
// OP_CALL3	19231	0	0
// OP_STORE_V	1	19362	0
// OP_ADDRESS	19361	680	19395
// OP_STOREP_F	31	19395	0
// OP_ADDRESS	19361	668	19396
// OP_STOREP_V	19362	19396	0
// OP_STORE_V	19362	4	0
// OP_CALL1	452	0	0
// OP_STORE_V	62	19374	0
// OP_STORE_V	59	19371	0
// OP_STORE_V	65	19377	0
// OP_LOAD_F	19361	683	19399
// OP_ADD_F	19363	19399	19400
// OP_STORE_F	19400	19363	0
// OP_STORE_V	19363	4	0
// OP_CALL1	3179	0	0
// OP_STORE_F	1	19363	0
// OP_STORE_F	213	19362	0
// OP_STORE_V	19362	4	0
// OP_CALL1	452	0	0
// OP_STORE_F	59	19380	0
// OP_STORE_F	60	19381	0
// OP_MUL_F	19380	19374	19401
// OP_MUL_F	19381	19375	19402
// OP_ADD_F	19401	19402	19403
// OP_MUL_F	276	19403	19404
// OP_DIV_F	19404	19376	19405
// OP_STORE_F	19405	19382	0
// OP_STORE_V	19380	4	0
// OP_CALL1	459	0	0
// OP_STORE_V	1	19380	0
// OP_LOAD_F	19361	682	19406
// OP_ADD_F	16131	19406	19407
// OP_MUL_VF	19380	19407	19408
// OP_STORE_V	19408	19365	0
// OP_ADD_F	19367	736	19411
// OP_LOAD_F	19361	684	19412
// OP_ADD_F	19411	19412	19413
// OP_STORE_F	19413	19367	0
// OP_LOAD_ENT	19361	667	19414
// OP_LOAD_V	19414	105	19415
// OP_LOAD_ENT	19361	667	19418
// OP_LOAD_V	19418	166	19419
// OP_ADD_V	19415	19419	19422
// OP_STORE_V	19422	19368	0
// OP_STORE_V	19368	4	0
// OP_ADD_V	19368	19365	19425
// OP_STORE_V	19425	7	0
// OP_STORE_V	214	10	0
// OP_LOAD_ENT	19361	667	19428
// OP_STORE_V	19428	13	0
// OP_CALL4	466	0	0
// OP_ADDRESS	19361	93	19429
// OP_STOREP_F	526	19429	0
// OP_STORE_V	19361	4	0
// OP_ADD_V	71	74	19430
// OP_LOAD_V	19361	166	19433
// OP_SUB_V	19430	19433	19436
// OP_STORE_V	19436	7	0
// OP_CALL2	453	0	0
// OP_LOAD_V	19361	175	19439
// OP_STORE_V	19439	4	0
// OP_CALL1	452	0	0
// OP_LOAD_F	19361	116	19442
// OP_GT	19442	214	19443
// OP_IFNOT	19443	5	0
// OP_ADDRESS	19361	684	19444
// OP_LOAD_F	19361	684	19445
// OP_ADD_F	19445	229	19446
// OP_STOREP_F	19446	19444	0
// OP_LOAD_F	19361	116	19447
// OP_LT	19447	276	19448
// OP_IFNOT	19448	5	0
// OP_ADDRESS	19361	684	19449
// OP_LOAD_F	19361	684	19450
// OP_SUB_F	19450	229	19451
// OP_STOREP_F	19451	19449	0
// OP_LOAD_F	19361	684	19452
// OP_GT	19452	219	19453
// OP_IFNOT	19453	3	0
// OP_ADDRESS	19361	684	19454
// OP_STOREP_F	219	19454	0
// OP_LOAD_F	19361	684	19455
// OP_LT	19455	16131	19456
// OP_IFNOT	19456	3	0
// OP_ADDRESS	19361	684	19457
// OP_STOREP_F	16131	19457	0
// OP_ADDRESS	19361	116	19458
// OP_STOREP_F	213	19458	0
// OP_STORE_F	213	61	0
// OP_LOAD_V	19361	113	19459
// OP_MUL_V	19459	59	19462
// OP_STORE_F	19462	19383	0
// OP_GT	19383	235	19463
// OP_IFNOT	19463	5	0
// OP_ADDRESS	19361	682	19464
// OP_LOAD_F	19361	682	19465
// OP_ADD_F	19465	229	19466
// OP_STOREP_F	19466	19464	0
// OP_LT	19383	12190	19467
// OP_IFNOT	19467	5	0
// OP_ADDRESS	19361	682	19468
// OP_LOAD_F	19361	682	19469
// OP_SUB_F	19469	229	19470
// OP_STOREP_F	19470	19468	0
// OP_LOAD_F	19361	682	19471
// OP_GT	19471	220	19472
// OP_IFNOT	19472	3	0
// OP_ADDRESS	19361	682	19473
// OP_STOREP_F	220	19473	0
// OP_LOAD_F	19361	682	19474
// OP_LT	19474	16131	19475
// OP_IFNOT	19475	3	0
// OP_ADDRESS	19361	682	19476
// OP_STOREP_F	16131	19476	0
// OP_STORE_F	213	67	0
// OP_LOAD_V	19361	113	19477
// OP_MUL_V	19477	65	19480
// OP_STORE_F	19480	19383	0
// OP_GT	19383	235	19481
// OP_IFNOT	19481	5	0
// OP_ADDRESS	19361	683	19482
// OP_LOAD_F	19361	683	19483
// OP_ADD_F	19483	229	19484
// OP_STOREP_F	19484	19482	0
// OP_LT	19383	12190	19485
// OP_IFNOT	19485	5	0
// OP_ADDRESS	19361	683	19486
// OP_LOAD_F	19361	683	19487
// OP_SUB_F	19487	229	19488
// OP_STOREP_F	19488	19486	0
// OP_ADDRESS	19361	683	19489
// OP_LOAD_F	19361	683	19490
// OP_STORE_V	19490	4	0
// OP_CALL1	3179	0	0
// OP_STOREP_F	1	19489	0
// OP_ADDRESS	19361	113	19491
// OP_STOREP_V	286	19491	0
// OP_STORE_V	19361	4	0
// OP_STORE_V	19361	7	0
// OP_CALL2	1059	0	0
// OP_STORE_V	19380	4	0
// OP_CALL1	495	0	0
// OP_STORE_V	1	19362	0
// OP_MUL_F	276	19362	19494
// OP_STORE_V	19494	4	0
// OP_CALL1	3179	0	0
// OP_STORE_F	1	19362	0
// OP_GT	19362	1296	19495
// OP_IFNOT	19495	3	0
// OP_SUB_F	19362	1298	19496
// OP_STORE_F	19496	19362	0
// OP_STORE_V	19361	4	0
// OP_STORE_V	19362	7	0
// OP_CALL2	1060	0	0
// OP_ADDRESS	19361	155	19497
// OP_STOREP_S	3002	19497	0
// OP_ADDRESS	19361	103	19498
// OP_STOREP_F	230	19498	0
// OP_ADDRESS	19361	182	19499
// OP_LOAD_F	19361	182	19500
// OP_BITOR	19500	223	19501
// OP_STOREP_F	19501	19499	0
// OP_DONE	0	0	0
void (entity globaldef006749) func002355 = 
{
    local vector globaldef006750;
    local vector globaldef006754;
    local vector globaldef006758;
    local vector globaldef006762;
    local vector globaldef006766;
    local vector globaldef006770;
    local vector globaldef006774;
    local float globaldef006778;
    globaldef006750 = globaldef006749.field000344.v_angle;
    
    if(globaldef006749.field000344.classname == "bot")
    {
        globaldef006750 = func002352(globaldef006749.field000345, globaldef006750, globaldef006749.field000357);
        globaldef006749.field000357 = time;
        globaldef006749.field000345 = globaldef006750;
    }
    
    makevectors(globaldef006750);
    globaldef006766 = v_up;
    globaldef006762 = v_forward;
    globaldef006770 = v_right;
    globaldef006750_y = globaldef006750_y + globaldef006749.field000358_y;
    globaldef006750_y = anglemod(globaldef006750_y);
    globaldef006750_x = FALSE;
    makevectors(globaldef006750);
    globaldef006774_x = v_forward_x;
    globaldef006774_y = v_forward_y;
    globaldef006774_z = (CONTENT_EMPTY * ((globaldef006774_x * globaldef006766_x) + (globaldef006774_y * globaldef006766_y))) / globaldef006766_z;
    globaldef006774 = normalize(globaldef006774);
    globaldef006754 = globaldef006774 * (-64 + globaldef006749.field000358_x);
    globaldef006754_z = (globaldef006754_z + OBOT_MAXBOTS) + globaldef006749.field000358_z;
    globaldef006758 = globaldef006749.field000344.origin + globaldef006749.field000344.view_ofs;
    traceline(globaldef006758, globaldef006758 + globaldef006754, TRUE, globaldef006749.field000344);
    globaldef006749.modelindex = globaldef000509;
    setorigin(globaldef006749, (trace_endpos + trace_plane_normal) - globaldef006749.view_ofs);
    makevectors(globaldef006749.v_angle);
    
    if(globaldef006749.velocity_z > TRUE)
    {
        globaldef006749.field000358_z = globaldef006749.field000358_z + MOVETYPE_STEP;
    }
    
    
    if(globaldef006749.velocity_z < CONTENT_EMPTY)
    {
        globaldef006749.field000358_z = globaldef006749.field000358_z - MOVETYPE_STEP;
    }
    
    
    if(globaldef006749.field000358_z > FL_MONSTER)
    {
        globaldef006749.field000358_z = FL_MONSTER;
    }
    
    
    if(globaldef006749.field000358_z < -64)
    {
        globaldef006749.field000358_z = -64;
    }
    
    globaldef006749.velocity_z = FALSE;
    v_forward_z = FALSE;
    globaldef006778 = globaldef006749.velocity * v_forward;
    
    if(globaldef006778 > MOVETYPE_BOUNCE)
    {
        globaldef006749.field000358_x = globaldef006749.field000358_x + MOVETYPE_STEP;
    }
    
    
    if(globaldef006778 < -10)
    {
        globaldef006749.field000358_x = globaldef006749.field000358_x - MOVETYPE_STEP;
    }
    
    
    if(globaldef006749.field000358_x > FL_GODMODE)
    {
        globaldef006749.field000358_x = FL_GODMODE;
    }
    
    
    if(globaldef006749.field000358_x < -64)
    {
        globaldef006749.field000358_x = -64;
    }
    
    v_right_z = FALSE;
    globaldef006778 = globaldef006749.velocity * v_right;
    
    if(globaldef006778 > MOVETYPE_BOUNCE)
    {
        globaldef006749.field000358_y = globaldef006749.field000358_y + MOVETYPE_STEP;
    }
    
    
    if(globaldef006778 < -10)
    {
        globaldef006749.field000358_y = globaldef006749.field000358_y - MOVETYPE_STEP;
    }
    
    globaldef006749.field000358_y = anglemod(globaldef006749.field000358_y);
    globaldef006749.velocity = VEC_ORIGIN;
    func002349(globaldef006749, globaldef006749);
    globaldef006750 = vectoangles(globaldef006774);
    globaldef006750_x = anglemod(CONTENT_EMPTY * globaldef006750_x);
    
    if(globaldef006750_x > 180)
    {
        globaldef006750_x = globaldef006750_x - 360;
    }
    
    func002350(globaldef006749, globaldef006750);
    globaldef006749.weaponmodel = "";
    globaldef006749.movetype = MOVETYPE_FLY;
    globaldef006749.flags = globaldef006749.flags | FL_ONGROUND;
};


// func002356
// function begins at statement 35666, parm_start=19502
// OP_LOAD_S	19502	129	19506
// OP_NE_S	19506	2025	19507
// OP_IFNOT	19507	2	0
// OP_RETURN	0	0	0
// OP_LOAD_ENT	19502	667	19508
// OP_EQ_E	19508	19502	19509
// OP_IFNOT	19509	16	0
// OP_ADDRESS	19502	93	19510
// OP_STOREP_F	526	19510	0
// OP_LOAD_F	19502	666	19511
// OP_BITAND	19511	762	19512
// OP_NOT_F	19512	0	19513
// OP_IFNOT	19513	3	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19117	0	0
// OP_LOAD_F	19502	666	19514
// OP_BITAND	19514	764	19515
// OP_NOT_F	19515	0	19516
// OP_IFNOT	19516	3	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19247	0	0
// OP_RETURN	0	0	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19142	0	0
// OP_LOAD_F	19502	666	19517
// OP_BITAND	19517	761	19518
// OP_IFNOT	19518	3	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19129	0	0
// OP_LOAD_F	19502	666	19519
// OP_BITAND	19519	763	19520
// OP_IFNOT	19520	4	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19360	0	0
// OP_GOTO	3	0	0
// OP_STORE_V	19502	4	0
// OP_CALL1	19310	0	0
// OP_DONE	0	0	0
void (entity globaldef006779) func002356 = 
{
    local vector globaldef006780;
    
    if(globaldef006779.classname != "observer")
    {
        return;
    }
    
    
    if(globaldef006779.field000344 == globaldef006779)
    {
        globaldef006779.modelindex = globaldef000509;
        
        if(!(globaldef006779.field000343 & globaldef000745))
        {
            func002345(globaldef006779);
        }
        
        
        if(!(globaldef006779.field000343 & globaldef000747))
        {
            func002353(globaldef006779);
        }
        
        return;
    }
    
    func002347(globaldef006779);
    
    if(globaldef006779.field000343 & globaldef000744)
    {
        func002346(globaldef006779);
    }
    
    if(globaldef006779.field000343 & globaldef000746)
    {
        func002355(globaldef006779);
    }
    else
    {
        func002354(globaldef006779);
    }
    
};


// func002357
// function begins at statement 35704, parm_start=19521
// OP_ADDRESS	19521	667	19522
// OP_STOREP_ENT	19521	19522	0
// OP_ADDRESS	19521	166	19523
// OP_STOREP_V	8450	19523	0
// OP_STORE_V	19521	4	0
// OP_LOAD_V	19521	672	19526
// OP_STORE_V	19526	7	0
// OP_CALL2	453	0	0
// OP_ADDRESS	19521	175	19529
// OP_LOAD_V	19521	676	19532
// OP_STOREP_V	19532	19529	0
// OP_STORE_V	19521	4	0
// OP_STORE_V	19521	7	0
// OP_CALL2	1059	0	0
// OP_STORE_V	19521	4	0
// OP_LOAD_V	19521	175	19535
// OP_STORE_V	19535	7	0
// OP_CALL2	1060	0	0
// OP_STORE_V	19521	4	0
// OP_STORE_V	289	7	0
// OP_STORE_V	292	10	0
// OP_CALL3	455	0	0
// OP_STORE_V	19521	4	0
// OP_STORE_V	3002	7	0
// OP_CALL2	852	0	0
// OP_STORE_V	19521	4	0
// OP_CALL1	19188	0	0
// OP_DONE	0	0	0
void (entity globaldef006784) func002357 = 
{
    globaldef006784.field000344 = globaldef006784;
    globaldef006784.view_ofs = '0 0 22';
    setorigin(globaldef006784, globaldef006784.field000349);
    globaldef006784.v_angle = globaldef006784.field000353;
    func002349(globaldef006784, globaldef006784);
    func002350(globaldef006784, globaldef006784.v_angle);
    setsize(globaldef006784, VEC_HULL_MIN, VEC_HULL_MAX);
    centerprint(globaldef006784, "");
    func002348(globaldef006784);
};

